### ISSUE TITLE
[BUG]I cant start Roblox with Bloxstrap

### ISSUE THREAD

**Issue by shumaikun0415** [pizzaboxer/bloxstrap#1111]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-01-13T11:28:32Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-01-13T11:28:32Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 6:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-01-13T11:28:32Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-01-13T11:28:32Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240113T112832Z.log
2024-01-13T11:28:32Z [Logger::Initialize] Finished initializing!
2024-01-13T11:28:32Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-01-13T11:28:32Z [JsonManager<Settings>::Load] Loaded successfully!
2024-01-13T11:28:32Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-01-13T11:28:32Z [JsonManager<State>::Load] Loaded successfully!
2024-01-13T11:28:32Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-01-13T11:28:32Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-01-13T11:28:32Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-01-13T11:28:32Z [App::OnStartup] Initializing bootstrapper
2024-01-13T11:28:32Z [App::OnStartup] Initializing bootstrapper dialog
2024-01-13T11:28:33Z [Bootstrapper::Run] Running bootstrapper
2024-01-13T11:28:33Z [Bootstrapper::Run] Performing connectivity check...
2024-01-13T11:28:33Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-01-13T11:28:33Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-01-13T11:28:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-01-13T11:28:34Z [Bootstrapper::Run] Connectivity check finished
2024-01-13T11:28:34Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-01-13T11:28:34Z [Bootstrapper::CheckForUpdates] No updates found
2024-01-13T11:28:34Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-01-13T11:28:34Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-01-13T11:28:34Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-01-13T11:28:34Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-rbxPkgManifest.txt
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-rbxPkgManifest.txt
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-rbxManifest.txt
2024-01-13T11:28:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-rbxManifest.txt
2024-01-13T11:28:35Z [Bootstrapper::SetStatus] Upgrading Roblox...
2024-01-13T11:28:35Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-01-13T11:28:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:28:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:28:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 13721414 bytes. (1/5)
2024-01-13T11:28:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): 指定されたデータの暗号化を解除できませんでした。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-13T11:28:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-01-13T11:28:37Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:28:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:28:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79306974 bytes. (2/5)
2024-01-13T11:28:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-13T11:28:53Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:28:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:29:32Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79306974 bytes. (3/5)
2024-01-13T11:29:32Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-13T11:29:32Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:29:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:29:46Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79306974 bytes. (4/5)
2024-01-13T11:29:46Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-13T11:29:46Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:29:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-88cfc23f4e7d4e4b-RobloxApp.zip
2024-01-13T11:30:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79306974 bytes. (5/5)
2024-01-13T11:30:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-13T11:30:02Z [App::OnStartup] Bootstrapper task has finished
2024-01-13T11:30:02Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-01-13T11:30:02Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-01-13T11:30:02Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Signature does not match!)
 ---> System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by shumaikun0415** [comment]
I tried to launch bloxstrap but It didnt work

**Comment by pizzaboxer** [comment]
Have you read through this Wiki page?
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
