### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by TheBlueShi** [pizzaboxer/bloxstrap#1191]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I checked the Wiki first, but it still did not work. I have tried to run as administrator, but it still does not work. the same error occurred when I was trying to install bloxstrap for the first time but i can fix it with just run as administrator, but now when upgrading Roblox, it happened again.

Here the logs: 2024-01-26T08:23:54Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-01-26T08:23:54Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 4:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-01-26T08:23:54Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-01-26T08:23:54Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240126T082354Z.log
2024-01-26T08:23:54Z [Logger::Initialize] Finished initializing!
2024-01-26T08:23:54Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20240119T080954Z.log'
2024-01-26T08:23:54Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-01-26T08:23:54Z [JsonManager<Settings>::Load] Loaded successfully!
2024-01-26T08:23:54Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-01-26T08:23:54Z [JsonManager<State>::Load] Loaded successfully!
2024-01-26T08:23:54Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-01-26T08:23:54Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-01-26T08:23:54Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-01-26T08:23:54Z [JsonManager<State>::Save] Save request ignored
2024-01-26T08:23:54Z [App::OnStartup] Initializing bootstrapper
2024-01-26T08:23:54Z [App::OnStartup] Initializing bootstrapper dialog
2024-01-26T08:23:54Z [App::OnStartup] Creating singleton mutex
2024-01-26T08:23:54Z [Bootstrapper::Run] Running bootstrapper
2024-01-26T08:23:54Z [Bootstrapper::Run] Performing connectivity check...
2024-01-26T08:23:54Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-01-26T08:23:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-01-26T08:23:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-01-26T08:23:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-01-26T08:23:57Z [Bootstrapper::Run] Connectivity check finished
2024-01-26T08:23:57Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-01-26T08:23:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-01-26T08:23:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-01-26T08:23:59Z [Bootstrapper::CheckForUpdates] No updates found
2024-01-26T08:23:59Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-01-26T08:23:59Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-01-26T08:23:59Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-01-26T08:23:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-01-26T08:24:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-01-26T08:24:00Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-01-26T08:24:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2355c01e37774010-rbxPkgManifest.txt
2024-01-26T08:24:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2355c01e37774010-rbxPkgManifest.txt
2024-01-26T08:24:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2355c01e37774010-rbxManifest.txt
2024-01-26T08:24:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2355c01e37774010-rbxManifest.txt
2024-01-26T08:24:01Z [Bootstrapper::SetStatus] Upgrading Roblox...
2024-01-26T08:24:01Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-01-26T08:24:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 5470787 bytes. (1/5)
2024-01-26T08:24:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-26T08:24:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-01-26T08:24:02Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:25Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80971667 bytes. (2/5)
2024-01-26T08:24:25Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-26T08:24:25Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80971667 bytes. (3/5)
2024-01-26T08:24:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-26T08:24:53Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:24:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:25:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80971667 bytes. (4/5)
2024-01-26T08:25:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-26T08:25:18Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:25:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-2355c01e37774010-RobloxApp.zip
2024-01-26T08:25:39Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80971667 bytes. (5/5)
2024-01-26T08:25:39Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-01-26T08:25:39Z [App::OnStartup] Bootstrapper task has finished
2024-01-26T08:25:39Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-01-26T08:25:39Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-01-26T08:25:39Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Signature does not match!)
 ---> System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
Besides the information given in the Wiki, there isn't really much else I can do to help you as of now, sorry.
