### ISSUE TITLE
[BUG] Bloxstrap starting and ater launching closing, but on background processor bloxstrap hes working

### ISSUE THREAD

**Issue by mapizzz** [pizzaboxer/bloxstrap#1196]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, i download bloxstrap and after launching he just crashing. No errors, just closing. What i need to do?

**Comment by pizzaboxer** [comment]
Can you confirm that Roblox without Bloxstrap works normally? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by mapizzz** [comment]
> Can you confirm that Roblox without Bloxstrap works normally? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

roblox without Bloxstrap works normally, but i need bloxstrap work

**Comment by pizzaboxer** [comment]
Are there any options in the Bloxstrap Menu that you've configured?

**Comment by monkeyboyquan** [comment]
hey, im having same issue

**Comment by pizzaboxer** [comment]
Can you start by answering all the questions I asked above?

**Comment by monkeyboyquan** [comment]
roblox without Bloxstrap works normally, but i need bloxstrap work.
Are there any options in the Bloxstrap Menu that you've configured?
nope ive used none. heres my log 

2024-03-08T08:45:56Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-03-08T08:46:00Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9213229 bytes total)
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\ExtraContent\LuaPackages\...
2024-03-08T08:46:00Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-03-08T08:46:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-translations.zip
2024-03-08T08:46:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-translations.zip
2024-03-08T08:46:00Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (364061 bytes total)
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-03-08T08:46:00Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-03-08T08:46:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-models.zip
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\ExtraContent\translations\...
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-03-08T08:46:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-models.zip
2024-03-08T08:46:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-03-08T08:46:06Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (8538593 bytes total)
2024-03-08T08:46:06Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-03-08T08:46:06Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-03-08T08:46:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-textures.zip
2024-03-08T08:46:06Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\ExtraContent\models\...
2024-03-08T08:46:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-97058ca6653344cd-extracontent-textures.zip
2024-03-08T08:46:06Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-03-08T08:46:11Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (10759972 bytes total)
2024-03-08T08:46:11Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-03-08T08:46:11Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-03-08T08:46:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-97058ca6653344cd-WebView2.zip
2024-03-08T08:46:11Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\ExtraContent\textures\...
2024-03-08T08:46:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-97058ca6653344cd-WebView2.zip
2024-03-08T08:46:11Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-03-08T08:46:11Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-03-08T08:46:11Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-03-08T08:46:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-97058ca6653344cd-WebView2RuntimeInstaller.zip
2024-03-08T08:46:11Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd...
2024-03-08T08:46:11Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-03-08T08:46:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-97058ca6653344cd-WebView2RuntimeInstaller.zip
2024-03-08T08:46:11Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-03-08T08:46:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-03-08T08:46:12Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-03-08T08:46:12Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-03-08T08:46:12Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-03-08T08:46:12Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-03-08T08:46:12Z [Bootstrapper::ApplyModifications] Roblox is running, aborting mod check
2024-03-08T08:46:12Z [Bootstrapper::Register] Registered application
2024-03-08T08:46:12Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-03-08T08:46:12Z [Bootstrapper::RegisterProgramSize] Registered as 507172 KB
2024-03-08T08:46:12Z [Bootstrapper::CheckInstall] Checking install
2024-03-08T08:46:12Z [App::OnStartup] Bootstrapper task has finished
2024-03-08T08:46:12Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-03-08T08:46:15Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-03-08T08:46:15Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
This isn't the same issue, you're getting an error message whereas OP isn't. Also, you should've read the Wiki. https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by monkeyboyquan** [comment]
hi that part of error was finished but when bloxstrap says "startinng roblox" about midway bloxstrap closes and runs as a background proccess, roblox didnt open whatsoever.

**Comment by pizzaboxer** [comment]
> roblox didnt open whatsoever.

Check to see if it's actually being caused by Bloxstrap first. https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by monkeyboyquan** [comment]
ya can u add me on discord and I can screenshare so you can futher understand? Heres my discord.
awakenedmangekyou

**Comment by pizzaboxer** [comment]
Did you do what I asked?
