### ISSUE TITLE
[BUG]  System.Security.SecurityException: Requested registry access is not allowed.

### ISSUE THREAD

**Issue by Wataheelew** [pizzaboxer/bloxstrap#1238]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-02-03T10:40:08Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-02-03T10:40:08Z [App::OnStartup] Compiled Friday, 3 November 2023 at 10:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-02-03T10:40:08Z [App::OnStartup] Loaded from %UserProfile%\Favorites\Länkar\Bloxstrap-v2.5.4.exe
2024-02-03T10:40:08Z [App::GlobalExceptionHandler] An exception occurred
2024-02-03T10:40:08Z [App::FinalizeExceptionHandling] System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Bloxstrap.InstallChecker..ctor()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
How/what did you use to download Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
