### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pathywathy** [pizzaboxer/bloxstrap#1396]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\username\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

2024-03-05T05:55:13Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-03-05T05:55:13Z [App::OnStartup] Compiled Friday, 3 November 2023 at 3:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-03-05T05:55:13Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-03-05T05:55:13Z [InstallChecker::FirstTimeRun] Running first-time install
2024-03-05T05:55:13Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240305T055513Z.log
2024-03-05T05:55:13Z [Logger::Initialize] Finished initializing!
2024-03-05T05:55:13Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-03-05T05:55:13Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-03-05T05:55:13Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\WINDOWS\system32\ClientSettings\ClientAppSettings.json'.
2024-03-05T05:55:13Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-03-05T05:55:13Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-03-05T05:55:13Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '144' is pending
2024-03-05T05:55:14Z [MainWindow::MainWindow] Initializing menu
2024-03-05T05:55:21Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=True)
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-03-05T05:55:21Z [RobloxDeployment::GetInfo] Getting extra information...
2024-03-05T05:55:21Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-03-05T05:55:21Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxPkgManifest.txt
2024-03-05T05:55:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxPkgManifest.txt
2024-03-05T05:55:21Z [RobloxDeployment::GetInfo] https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxPkgManifest.txt - Last-Modified: Thu, 29 Feb 2024 22:07:02 GMT
2024-03-05T05:55:27Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-03-05T05:55:27Z [App::OnStartup] Initializing bootstrapper
2024-03-05T05:55:27Z [App::OnStartup] Initializing bootstrapper dialog
2024-03-05T05:55:27Z [App::OnStartup] Creating singleton mutex
2024-03-05T05:55:27Z [Bootstrapper::Run] Running bootstrapper
2024-03-05T05:55:27Z [Bootstrapper::Run] Performing connectivity check...
2024-03-05T05:55:27Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-03-05T05:55:27Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-03-05T05:55:27Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-03-05T05:55:27Z [Bootstrapper::Run] Connectivity check finished
2024-03-05T05:55:27Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-03-05T05:55:27Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxPkgManifest.txt
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxPkgManifest.txt
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxManifest.txt
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-rbxManifest.txt
2024-03-05T05:55:27Z [Bootstrapper::SetStatus] Installing Roblox...
2024-03-05T05:55:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-RobloxApp.zip
2024-03-05T05:55:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-RobloxApp.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (77014089 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-avatar.zip
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-avatar.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (465127 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-configs.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\avatar\...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-configs.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (45958 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-fonts.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\configs\...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-fonts.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6060378 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-models.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\fonts\...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-models.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488738 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-sky.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\models\...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-sky.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-sounds.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\sky\...
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-sounds.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-shaders.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\sounds\...
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-shaders.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (3373461 bytes total)
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-03-05T05:55:32Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-03-05T05:55:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-ssl.zip
2024-03-05T05:55:32Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\shaders\...
2024-03-05T05:55:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-ssl.zip
2024-03-05T05:55:33Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (131397 bytes total)
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-03-05T05:55:33Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-03-05T05:55:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-textures2.zip
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ssl\...
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-03-05T05:55:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-textures2.zip
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-03-05T05:55:33Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (9355212 bytes total)
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-03-05T05:55:33Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-03-05T05:55:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-textures3.zip
2024-03-05T05:55:33Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\textures\...
2024-03-05T05:55:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-textures3.zip
2024-03-05T05:55:35Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (28516580 bytes total)
2024-03-05T05:55:35Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-03-05T05:55:35Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-03-05T05:55:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-terrain.zip
2024-03-05T05:55:35Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\PlatformContent\pc\textures\...
2024-03-05T05:55:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-terrain.zip
2024-03-05T05:55:35Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-03-05T05:55:36Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (31003769 bytes total)
2024-03-05T05:55:36Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-03-05T05:55:36Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-03-05T05:55:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-platform-fonts.zip
2024-03-05T05:55:36Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\PlatformContent\pc\terrain\...
2024-03-05T05:55:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-content-platform-fonts.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-03-05T05:55:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-places.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\PlatformContent\pc\fonts\...
2024-03-05T05:55:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-places.zip
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1027122 bytes total)
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-03-05T05:55:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-luapackages.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ExtraContent\places\...
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-03-05T05:55:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-luapackages.zip
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9213220 bytes total)
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-03-05T05:55:37Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-03-05T05:55:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-translations.zip
2024-03-05T05:55:37Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ExtraContent\LuaPackages\...
2024-03-05T05:55:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-translations.zip
2024-03-05T05:55:38Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (359906 bytes total)
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-03-05T05:55:38Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-03-05T05:55:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-models.zip
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ExtraContent\translations\...
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-03-05T05:55:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-models.zip
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-03-05T05:55:38Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (8499682 bytes total)
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-03-05T05:55:38Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-03-05T05:55:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-textures.zip
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ExtraContent\models\...
2024-03-05T05:55:38Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-03-05T05:55:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-extracontent-textures.zip
2024-03-05T05:55:39Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (10759972 bytes total)
2024-03-05T05:55:39Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-03-05T05:55:39Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-03-05T05:55:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-WebView2.zip
2024-03-05T05:55:39Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\ExtraContent\textures\...
2024-03-05T05:55:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-WebView2.zip
2024-03-05T05:55:39Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-03-05T05:55:39Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-03-05T05:55:39Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-03-05T05:55:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-bca459bcd1854ce4-WebView2RuntimeInstaller.zip
2024-03-05T05:55:39Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4...
2024-03-05T05:55:39Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-03-05T05:55:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-bca459bcd1854ce4-WebView2RuntimeInstaller.zip
2024-03-05T05:55:39Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-03-05T05:55:40Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-03-05T05:55:41Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-03-05T05:55:41Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-03-05T05:55:41Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-03-05T05:55:41Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-03-05T05:55:41Z [Bootstrapper::ApplyModifications] Roblox is running, aborting mod check
2024-03-05T05:55:41Z [Bootstrapper::Register] Registered application
2024-03-05T05:55:41Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-03-05T05:55:41Z [Bootstrapper::RegisterProgramSize] Registered as 503934 KB
2024-03-05T05:55:41Z [Bootstrapper::CheckInstall] Checking install
2024-03-05T05:55:41Z [App::OnStartup] Bootstrapper task has finished
2024-03-05T05:55:41Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-03-05T05:55:41Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-03-05T05:55:41Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
Can you please read the preliminary instructions before posting?

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
