### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NETLA8** [pizzaboxer/bloxstrap#1422]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/162830892/1bec56cd-f9e9-42a0-bdd0-d3397e2c4bca)
2024-03-09T18:21:19Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-03-09T18:21:19Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 4:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-03-09T18:21:19Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-03-09T18:21:19Z [Logger::Initialize] Initializing at C:\Users\Семён\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240309T182119Z.log
2024-03-09T18:21:19Z [App::GlobalExceptionHandler] An exception occurred
2024-03-09T18:21:19Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\Семён\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240309T182119Z.log' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
Do you have any antivirus software that can potentially be preventing Bloxstrap from creating files?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
