### ISSUE TITLE
Bloxstrap not detecting the right location [BUG] 

### ISSUE THREAD

**Issue by MikeyMayukhYT** [pizzaboxer/bloxstrap#1473]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have changed my windows username folder so i think bloxstrap couldnt change with it so this is the problem . now how to fix this?

LOG:
2024-03-21T12:37:47Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-03-21T12:37:47Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 3:16:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-03-21T12:37:47Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-03-21T12:37:47Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-03-21T12:37:47Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-03-21T12:37:47Z [Logger::Initialize] Initializing at C:\Users\Mima\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240321T123747Z.log
2024-03-21T12:37:47Z [App::GlobalExceptionHandler] An exception occurred
2024-03-21T12:37:47Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\Mima\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

this above log says that my user is Mima but i have changed it to MikeyMayukh. Someone help me fix this
![image](https://github.com/pizzaboxer/bloxstrap/assets/77010784/8cce7647-1d27-4f8a-bb9b-6989ae801e89)

**Comment by pizzaboxer** [comment]
> this above log says that my user is Mima but i have changed it to MikeyMayukh.

You'll need to change Bloxstrap's install location by opening the registry editor, going to `HKEY_CURRENT_USER\Software\Bloxstrap`, and updating the InstallLocation key accordingly.
