### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SdVt12** [pizzaboxer/bloxstrap#1601]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-04-11T11:54:44Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-11T11:54:44Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 2:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-11T11:54:44Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4_1.exe
2024-04-11T11:54:44Z [InstallChecker::FirstTimeRun] Running first-time install
2024-04-11T11:54:44Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240411T115444Z.log
2024-04-11T11:54:44Z [Logger::Initialize] Finished initializing!
2024-04-11T11:54:44Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-04-11T11:54:44Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-04-11T11:54:44Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\Downloads\ClientSettings\ClientAppSettings.json'.
2024-04-11T11:54:44Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-04-11T11:54:44Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-04-11T11:54:44Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-04-11T11:54:44Z [MainWindow::MainWindow] Initializing menu
2024-04-11T11:55:29Z [FastFlagManager::SetValue] Changing of 'DFIntTaskSchedulerTargetFps' from '120' to '1200' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagDisableNewIGMinDUA' to 'True' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableInGameMenuControls' to 'False' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableInGameMenuModernization' to 'False' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableMenuControlsABTest' to 'False' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableMenuModernizationABTest' to 'False' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableMenuModernizationABTest2' to 'False' is pending
2024-04-11T11:55:51Z [FastFlagManager::SetValue] Setting of 'FFlagEnableV3MenuABTest3' to 'False' is pending
2024-04-11T11:55:55Z [FastFlagManager::SetValue] Setting of 'DFIntCanHideGuiGroupId' to '32380007' is pending
2024-04-11T11:55:56Z [FastFlagManager::SetValue] Deletion of 'DFIntCanHideGuiGroupId' is pending
2024-04-11T11:55:56Z [FastFlagManager::SetValue] Setting of 'DFIntCanHideGuiGroupId' to '32380007' is pending
2024-04-11T11:55:57Z [FastFlagManager::SetValue] Deletion of 'DFIntCanHideGuiGroupId' is pending
2024-04-11T11:56:02Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-04-11T11:56:02Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-04-11T11:56:02Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-04-11T11:56:02Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-04-11T11:56:32Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=True)
2024-04-11T11:56:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-11T11:56:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-11T11:56:33Z [RobloxDeployment::GetInfo] Getting extra information...
2024-04-11T11:56:33Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-04-11T11:56:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-04-11T11:56:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-04-11T11:56:33Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-04-11T11:56:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-11T11:56:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-11T11:56:33Z [RobloxDeployment::GetInfo] https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt - Last-Modified: Tue, 09 Apr 2024 20:17:58 GMT
2024-04-11T11:56:40Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-04-11T11:56:40Z [App::OnStartup] Initializing bootstrapper
2024-04-11T11:56:40Z [App::OnStartup] Initializing bootstrapper dialog
2024-04-11T11:56:40Z [Bootstrapper::Run] Running bootstrapper
2024-04-11T11:56:40Z [Bootstrapper::Run] Performing connectivity check...
2024-04-11T11:56:40Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-04-11T11:56:40Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-11T11:56:40Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-11T11:56:40Z [Bootstrapper::Run] Connectivity check finished
2024-04-11T11:56:40Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-11T11:56:40Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-11T11:56:40Z [Bootstrapper::SetStatus] Installing Roblox...
2024-04-11T11:56:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:56:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:56:41Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 441633 bytes. (1/5)
2024-04-11T11:56:41Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): Указанные данные не могут быть расшифрованы.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-11T11:56:41Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-04-11T11:56:41Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:56:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:56:59Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80015930 bytes. (2/5)
2024-04-11T11:56:59Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-11T11:56:59Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:56:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:57:30Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80015930 bytes. (3/5)
2024-04-11T11:57:30Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-11T11:57:30Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:57:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:57:48Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80015930 bytes. (4/5)
2024-04-11T11:57:48Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-11T11:57:48Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:57:48Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-11T11:58:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80015930 bytes. (5/5)
2024-04-11T11:58:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-11T11:58:07Z [App::OnStartup] Bootstrapper task has finished
2024-04-11T11:58:07Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-04-11T11:58:07Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-04-11T11:58:07Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Signature does not match!)
 ---> System.Exception: Signature does not match!
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
