### ISSUE TITLE
"Installing Roblox" stuck

### ISSUE THREAD

**Issue by nnxj3** [pizzaboxer/bloxstrap#1627]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i Ran the "Play Roblox" app for some reason it just says "installing Roblox" and its stuck like that even though roblox is already installed on my computer. i dont have any fast flags.
![Screenshot 2024-04-17 005104](https://github.com/pizzaboxer/bloxstrap/assets/167169686/31cbadf9-acee-4df4-a277-4570a19bbf1f)

**Comment by pizzaboxer** [comment]
> When i Ran the "Play Roblox" app for some reason it just says "installing Roblox" and its stuck like that even though roblox is already installed on my computer.

Bloxstrap installs Roblox independently of the original launcher. If it's stuck though, then I'll need to take a look at the log files. Are you able to open the `%localappdata%\Bloxstrap\Logs` folder? If so, then get the latest log file from there (either at the top or bottom) and send it here.

**Comment by nnxj3** [comment]
2024-04-17T00:40:27Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-17T00:40:27Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 12:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-17T00:40:27Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-04-17T00:40:27Z [InstallChecker::FirstTimeRun] Running first-time install
2024-04-17T00:40:27Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240417T004027Z.log
2024-04-17T00:40:27Z [Logger::Initialize] Finished initializing!
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Windows\system32\ClientSettings\ClientAppSettings.json'.
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-04-17T00:40:27Z [MainWindow::MainWindow] Initializing menu
2024-04-17T00:40:37Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-04-17T00:40:37Z [App::OnStartup] Initializing bootstrapper
2024-04-17T00:40:37Z [App::OnStartup] Initializing bootstrapper dialog
2024-04-17T00:40:37Z [Bootstrapper::Run] Running bootstrapper
2024-04-17T00:40:37Z [Bootstrapper::Run] Performing connectivity check...
2024-04-17T00:40:37Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-17T00:40:37Z [Bootstrapper::Run] Connectivity check finished
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-17T00:40:37Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-04-17T00:40:38Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-17T00:40:39Z [Bootstrapper::SetStatus] Installing Roblox...
2024-04-17T00:40:39Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-04-17T00:40:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 7310466 bytes. (1/5)
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-04-17T00:40:40Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:49:21Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79999056 bytes. (2/5)
2024-04-17T00:49:21Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 16874 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:49:21Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:49:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:57:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80000354 bytes. (3/5)
2024-04-17T00:57:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 15576 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:57:53Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:57:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:06:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80010738 bytes. (4/5)
2024-04-17T01:06:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 5192 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T01:06:27Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:06:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:15:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80005546 bytes. (5/5)
2024-04-17T01:15:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 10384 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T01:15:00Z [App::OnStartup] Bootstrapper task has finished
2024-04-17T01:15:00Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-04-17T01:15:00Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-04-17T01:15:00Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The response ended prematurely, with at least 10384 additional bytes expected.)
 ---> System.IO.IOException: The response ended prematurely, with at least 10384 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
2024-04-17T02:53:31Z [Bootstrapper::CancelInstall] Cancelling install...
2024-04-17T02:53:31Z [App::Terminate] Terminating with exit code 1602 (ERROR_INSTALL_USEREXIT)
@pizzaboxer

**Comment by nnxj3** [comment]
> > When i Ran the "Play Roblox" app for some reason it just says "installing Roblox" and its stuck like that even though roblox is already installed on my computer.
> 
> Bloxstrap installs Roblox independently of the original launcher. If it's stuck though, then I'll need to take a look at the log files. Are you able to open the `%localappdata%\Bloxstrap\Logs` folder? If so, then get the latest log file from there (either at the top or bottom) and send it here.

2024-04-17T00:40:27Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-17T00:40:27Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 12:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-17T00:40:27Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-04-17T00:40:27Z [InstallChecker::FirstTimeRun] Running first-time install
2024-04-17T00:40:27Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240417T004027Z.log
2024-04-17T00:40:27Z [Logger::Initialize] Finished initializing!
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-04-17T00:40:27Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Windows\system32\ClientSettings\ClientAppSettings.json'.
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-04-17T00:40:27Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-04-17T00:40:27Z [MainWindow::MainWindow] Initializing menu
2024-04-17T00:40:37Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-04-17T00:40:37Z [App::OnStartup] Initializing bootstrapper
2024-04-17T00:40:37Z [App::OnStartup] Initializing bootstrapper dialog
2024-04-17T00:40:37Z [Bootstrapper::Run] Running bootstrapper
2024-04-17T00:40:37Z [Bootstrapper::Run] Performing connectivity check...
2024-04-17T00:40:37Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-17T00:40:37Z [Bootstrapper::Run] Connectivity check finished
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-17T00:40:37Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-17T00:40:37Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-04-17T00:40:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-04-17T00:40:38Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxPkgManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-17T00:40:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-rbxManifest.txt
2024-04-17T00:40:39Z [Bootstrapper::SetStatus] Installing Roblox...
2024-04-17T00:40:39Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-04-17T00:40:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 7310466 bytes. (1/5)
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:40:40Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-04-17T00:40:40Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:40:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:49:21Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 79999056 bytes. (2/5)
2024-04-17T00:49:21Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 16874 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:49:21Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:49:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:57:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80000354 bytes. (3/5)
2024-04-17T00:57:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 15576 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T00:57:53Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T00:57:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:06:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80010738 bytes. (4/5)
2024-04-17T01:06:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 5192 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T01:06:27Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:06:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-8950870ea20941f9-RobloxApp.zip
2024-04-17T01:15:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 80005546 bytes. (5/5)
2024-04-17T01:15:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The response ended prematurely, with at least 10384 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-04-17T01:15:00Z [App::OnStartup] Bootstrapper task has finished
2024-04-17T01:15:00Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-04-17T01:15:00Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-04-17T01:15:00Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The response ended prematurely, with at least 10384 additional bytes expected.)
 ---> System.IO.IOException: The response ended prematurely, with at least 10384 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
2024-04-17T02:53:31Z [Bootstrapper::CancelInstall] Cancelling install...
2024-04-17T02:53:31Z [App::Terminate] Terminating with exit code 1602 (ERROR_INSTALL_USEREXIT)

**Comment by nnxj3** [comment]
> Strange that the error dialog didn't show here, though the planned refactoring should fix that anyway.
> 
> This is showing that your download progress keeps getting interrupted. Is this happening every time you try to run it? If so, then check to make sure the original Roblox launcher works (https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap). If it does, then it seems like your antivirus or some other software is conflicting with Bloxstrap.

I have a speculation on why that happens, i had a hard time downloading Roblox on my computer because the download kept getting interrupted. I contacted roblox support and it turns out it was some sort of internet issue, and when i used ethernet instead of wireless wifi it fixed it.

**Comment by pizzaboxer** [comment]
Try doing that here and see if it works.

**Comment by nnxj3** [comment]
> Try doing that here and see if it works.

I used an ethernet cable and its working completely fine now.
