### ISSUE TITLE
[BUG] An Exception Occured While Running Bloxstrap

### ISSUE THREAD

**Issue by soundwaw** [pizzaboxer/bloxstrap#1652]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When ever i try to run a roblox game or try to open the bloxstrap menu im met by 
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/aa3f4e21-a70c-4d8e-b42f-d775b0088959) 
System.Security.SecurityException: Requested registry access is not allowed. 

is there a solution? this is a problem with bloxstrap. I uninstalled bloxstrap and roblox worked perfectly fine. 

2024-04-20T13:15:05Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-20T13:15:05Z [App::OnStartup] Compiled Friday, 3 November 2023 at 10:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-20T13:15:05Z [App::OnStartup] Loaded from %UserProfile%\Favorites\Bloxstrap\Bloxstrap.exe
2024-04-20T13:15:05Z [App::GlobalExceptionHandler] An exception occurred
2024-04-20T13:15:05Z [App::FinalizeExceptionHandling] System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Bloxstrap.InstallChecker..ctor()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
Seems like an issue with your antivirus.

**Comment by soundwaw** [comment]
i dont know if im doing something wrong, but when i turn off my antivirus it still doesnt work 
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/50ede47a-7fe6-4987-8aed-bf41f3a48fa1)
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/a134e6e9-051f-4308-855a-a847e67e4d51)

**Comment by pizzaboxer** [comment]
> i dont know if im doing something wrong, but when i turn off my antivirus it still doesnt work

Something is still messing with it because it's still unable to read the Windows Registry.

**Comment by Kerim14124** [comment]
@pizzaboxer same thing is happening to me but i dont have an antivirus + i cant lanch roblox normally

**Comment by soundwaw** [comment]
> @pizzaboxer same thing is happening to me but i dont have an antivirus + i cant lanch roblox normally

there is a solution to launch roblox normally
first right click the roblox name/icon in search bar and open the files (second alternative)
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/98e39f22-3e56-48bc-90a4-814a54973d4b)

then right click the roblox player and click the third alternative (open files)
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/1280588a-a2d7-4d67-9f11-de6a143c43bd)

then just double click on robloxplayerlauncher 
![image](https://github.com/pizzaboxer/bloxstrap/assets/167618993/1588dbb4-d7bc-4ceb-a44e-b00ac2be26b7)

**Comment by Kerim14124** [comment]
still dosent work

**Comment by pizzaboxer** [comment]
>  i cant lanch roblox normally

Can't really help you there since that's an issue with Roblox itself. Reading https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch might help.
