### ISSUE TITLE
[BUG] an annoying bug

### ISSUE THREAD

**Issue by gkritsovas** [pizzaboxer/bloxstrap#1658]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Bloxstrap-v2 5 4_KEfG8kZmQU](https://github.com/pizzaboxer/bloxstrap/assets/167632784/7d250895-14d0-4d1c-afae-bb222d196156)

I don't know what to do, I reinstall bloxstrap nothing. I delete the file nothing. I am not sure what to do now

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by gkritsovas** [comment]
2024-04-21T12:05:42Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-21T12:05:42Z [App::OnStartup] Compiled Friday, 3 November 2023 at 11:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-21T12:05:42Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-04-21T12:05:42Z [InstallChecker::FirstTimeRun] Running first-time install
2024-04-21T12:05:42Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240421T120542Z.log
2024-04-21T12:05:42Z [Logger::Initialize] Finished initializing!
2024-04-21T12:05:42Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-04-21T12:05:42Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-04-21T12:05:42Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\Downloads\ClientSettings\ClientAppSettings.json'.
2024-04-21T12:05:42Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-04-21T12:05:42Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-04-21T12:05:42Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '150' is pending
2024-04-21T12:05:43Z [MainWindow::MainWindow] Initializing menu
2024-04-21T12:05:59Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-04-21T12:05:59Z [App::OnStartup] Initializing bootstrapper
2024-04-21T12:05:59Z [App::OnStartup] Initializing bootstrapper dialog
2024-04-21T12:05:59Z [Bootstrapper::Run] Running bootstrapper
2024-04-21T12:05:59Z [Bootstrapper::Run] Performing connectivity check...
2024-04-21T12:05:59Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-04-21T12:05:59Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-21T12:05:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-21T12:05:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-21T12:05:59Z [Bootstrapper::Run] Connectivity check finished
2024-04-21T12:05:59Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-21T12:05:59Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-21T12:05:59Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-04-21T12:05:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-04-21T12:06:00Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-rbxPkgManifest.txt
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-rbxPkgManifest.txt
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-rbxManifest.txt
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-rbxManifest.txt
2024-04-21T12:06:00Z [Bootstrapper::SetStatus] Installing Roblox...
2024-04-21T12:06:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-RobloxApp.zip
2024-04-21T12:06:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-RobloxApp.zip
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (80808809 bytes total)
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-avatar.zip
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659...
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-avatar.zip
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402522 bytes total)
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-configs.zip
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\avatar\...
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-configs.zip
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (89975 bytes total)
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-04-21T12:06:04Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-fonts.zip
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\configs\...
2024-04-21T12:06:04Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-04-21T12:06:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-fonts.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6780428 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-models.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\fonts\...
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-models.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-sky.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\models\...
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-sky.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-sounds.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\sky\...
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-sounds.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-shaders.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\sounds\...
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-shaders.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (3703173 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-ssl.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\shaders\...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-ssl.zip
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (133126 bytes total)
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-04-21T12:06:05Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-textures2.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ssl\...
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-04-21T12:06:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-textures2.zip
2024-04-21T12:06:05Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-04-21T12:06:06Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (9394342 bytes total)
2024-04-21T12:06:06Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-04-21T12:06:06Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-04-21T12:06:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-textures3.zip
2024-04-21T12:06:06Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\textures\...
2024-04-21T12:06:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-textures3.zip
2024-04-21T12:06:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (28516580 bytes total)
2024-04-21T12:06:07Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-04-21T12:06:07Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-04-21T12:06:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-terrain.zip
2024-04-21T12:06:07Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\PlatformContent\pc\textures\...
2024-04-21T12:06:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-terrain.zip
2024-04-21T12:06:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-04-21T12:06:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (31003769 bytes total)
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-content-platform-fonts.zip
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\PlatformContent\pc\terrain\...
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-content-platform-fonts.zip
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-places.zip
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\PlatformContent\pc\fonts\...
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-places.zip
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1027122 bytes total)
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-04-21T12:06:10Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-luapackages.zip
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ExtraContent\places\...
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-04-21T12:06:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-04-21T12:06:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-luapackages.zip
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9211870 bytes total)
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-translations.zip
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ExtraContent\LuaPackages\...
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-translations.zip
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (388370 bytes total)
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-models.zip
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ExtraContent\translations\...
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-models.zip
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (8755547 bytes total)
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-04-21T12:06:11Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-textures.zip
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ExtraContent\models\...
2024-04-21T12:06:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-04-21T12:06:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-extracontent-textures.zip
2024-04-21T12:06:12Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (14111882 bytes total)
2024-04-21T12:06:12Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-04-21T12:06:12Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-04-21T12:06:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-WebView2.zip
2024-04-21T12:06:12Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\ExtraContent\textures\...
2024-04-21T12:06:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-WebView2.zip
2024-04-21T12:06:12Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-04-21T12:06:12Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-04-21T12:06:12Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-04-21T12:06:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-492b7f0827474659-WebView2RuntimeInstaller.zip
2024-04-21T12:06:12Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659...
2024-04-21T12:06:12Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-04-21T12:06:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-492b7f0827474659-WebView2RuntimeInstaller.zip
2024-04-21T12:06:12Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-04-21T12:06:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-04-21T12:06:13Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-04-21T12:06:13Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-04-21T12:06:13Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-04-21T12:06:13Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-04-21T12:06:13Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-04-21T12:06:13Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-04-21T12:06:13Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-04-21T12:06:13Z [Bootstrapper::CheckModPreset.Sounds.OldDeath.ogg] Writing 'content\sounds\ouch.ogg' as preset is enabled, and mod file does not exist or does not match preset
2024-04-21T12:06:13Z [App::OnStartup] Bootstrapper task has finished
2024-04-21T12:06:13Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-04-21T12:06:13Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-04-21T12:06:13Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The file '%UserProfile%\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' already exists.)
 ---> System.IO.IOException: The file '%UserProfile%\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
When you were installing Bloxstrap, did you choose a custom font? If so, what file path did you choose?

**Comment by gkritsovas** [comment]
appdata

**Comment by gkritsovas** [comment]
in documents?

**Comment by gkritsovas** [comment]
appdata roaming

**Comment by pizzaboxer** [comment]
Don't choose a font when you install for the first time. It should automatically apply after installation.
