### ISSUE TITLE
System.Diagnostics.GetProcesses() causing an integer overflow [D]

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#1679]
https://discord.com/channels/1099468797410283540/1170533566128590868

This is a bug with .NET internals, might need to check to see if it's been fixed in newer .NET versions or not

**Comment by bluepilledgreat** [comment]
Log:
```
2023-11-05T03:31:33Z [App::OnStartup] Starting Bloxstrap v2.5.4
2023-11-05T03:31:33Z [App::OnStartup] Compiled Friday, 3 November 2023 at 6:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2023-11-05T03:31:33Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2023-11-05T03:31:33Z [App::OnStartup] Started with IsMenuLaunch flag
2023-11-05T03:31:33Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20231105T033133Z.log
2023-11-05T03:31:33Z [Logger::Initialize] Finished initializing!
2023-11-05T03:31:33Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-11-05T03:31:33Z [JsonManager<Settings>::Load] Loaded successfully!
2023-11-05T03:31:33Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-11-05T03:31:33Z [JsonManager<State>::Load] Loaded successfully!
2023-11-05T03:31:33Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-11-05T03:31:33Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2023-11-05T03:31:33Z [App::GlobalExceptionHandler] An exception occurred
2023-11-05T03:31:33Z [App::FinalizeExceptionHandling] System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(ReadOnlySpan`1 data, Nullable`1 processIdFilter)
   at System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(Nullable`1 processIdFilter)
   at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
   at System.Diagnostics.Process.GetProcesses(String machineName)
   at System.Diagnostics.Process.GetProcesses()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
