### ISSUE TITLE
Opening bloxstrap for the first time just opens it then closes it

### ISSUE THREAD

**Issue by Variable1485** [pizzaboxer/bloxstrap#170]
Seen it opening on task manager then closing a second later, I checked logs and the only thing i see is this
![image](https://user-images.githubusercontent.com/68739273/235308157-9a6d394d-fe01-4c08-afa7-cb72286cb052.png)

**Comment by Variable1485** [comment]
fyi, successful winget install and opening bloxstrap still does nothing, this log is coming from my retry with the github installer (.NET 6 is installed)

**Comment by pizzaboxer** [comment]
Looks like it's definitely related to the user interface in some way. Can I quickly check which version of the runtime you have installed?
![image](https://user-images.githubusercontent.com/41478239/235308268-de28d668-bc8e-4659-af5c-bf65a3148a95.png)

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/235308377-37e4af71-0963-42e6-97af-453b039e214f.png)
dang, there are multiple old ones that i think came from me installing other stuff requiring .NET, do i need to uninstall the old ones?

**Comment by pizzaboxer** [comment]
I don't think they should affect anything, but if you want to try and uninstall just the first one, go ahead.

**Comment by Variable1485** [comment]
done, unless i need to restart bloxstrap still crashes

**Comment by pizzaboxer** [comment]
Let me try and obtain the exit code that Bloxstrap returns when it crashes. Open the command prompt and run these two commands:

```cmd
start /wait %localappdata%\Bloxstrap\Bloxstrap.exe -menu
echo %errorlevel%
```

**Comment by Variable1485** [comment]
output was -532462766

**Comment by pizzaboxer** [comment]
That's `0xe0434352` in hex, which is the exact same error code as other people were having, which looks like another runtime problem. 

Can you open the Windows Event Viewer, go to Windows Logs -> Application, and see if there's any recent error logs?

**Comment by Variable1485** [comment]
aha! i found the error log:
`Application: Bloxstrap.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Wpf.Ui.Interop.Dwmapi.DwmGetColorizationParameters(DWMCOLORIZATIONPARAMS& dwParameters)
   at Wpf.Ui.Interop.UnsafeNativeMethods.GetDwmColor()
   at Wpf.Ui.Appearance.Accent.GetColorizationColor()
   at Wpf.Ui.Appearance.Accent.ApplySystemAccent()
   at Wpf.Ui.Mvvm.Services.ThemeService.SetSystemAccent()
   at Bloxstrap.Dialogs.FluentDialog..ctor()
   at Bloxstrap.Enums.BootstrapperStyleEx.GetNew(BootstrapperStyle bootstrapperStyle)
   at Bloxstrap.App.GlobalExceptionHandler(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Bloxstrap.App.Main()
`

**Comment by pizzaboxer** [comment]
Well, I am at a loss for words right now. Somehow Windows is just not able to find dwmapi.dll. What does doing `where dwmapi.dll` in the Command Prompt show?

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/235310174-f3160ab1-7413-4618-94ea-affab61bdb50.png)
it seems to be fine

**Comment by pizzaboxer** [comment]
Looks like this has been a problem for this library going as far back as July 2022 (lepoco/wpfui#275). I can try and make a workaround for this in the upcoming update, but for now, I can suggest a fairly hacky solution. You won't be able to open the menu, but you should at the very least be able to launch Roblox.

Edit Settings.json in the folder, and change
```json
"BootstrapperStyle": 4
```
to
```json
"BootstrapperStyle": 3
```

If you need to configure Bloxstrap, looking through the JSON file should hopefully be clear enough. Ask me if you need help with anything.

**Comment by Variable1485** [comment]
Alright, I'll do that when free and will inform you if it works before closing. Thanks for your help and quick response! Much appreciated.

**Comment by pizzaboxer** [comment]
Don't close this, I'll keep this open until the fix for this has actually been released. That's usually what I do.

**Comment by Variable1485** [comment]
The workaround worked, thanks!

**Comment by pizzaboxer** [comment]
If you're still there, I'd like to see if this build works for you. Just try and run it, see if anything happens.

https://pizzaboxer.xyz/files/bloxstrap-debug/170/Bloxstrap.exe

**Comment by pizzaboxer** [comment]
I just verified that this should be fixed as #173 had this same problem, but just want to check here to be sure.

**Comment by Variable1485** [comment]
Lemme check all this real quick

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/235429354-67e44881-736d-4df4-81ca-351f4e217601.png)
I think this is because bootstrapper style being valued 3, I'll try with four real quick

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/235429588-17cea9e5-7314-416e-b75e-8c4d2b380639.png)
That worked!

**Comment by Variable1485** [comment]
Glad to say that your fix works now, I read the issue thread that you referred and replaced the bloxstrap exe

**Comment by pizzaboxer** [comment]
Awesome, I'll close this now since I have this marked in the 2.3.0 todo.
