### ISSUE TITLE
[BUG] Bloxstrap

### ISSUE THREAD

**Issue by Reuben124** [pizzaboxer/bloxstrap#1714]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am not able get into servers or play games. It keeps saying "An exception occurred while running Bloxstrap". It said i should copy the log file so here it is.
[Bloxstrap_20240430T145618Z.log](https://github.com/pizzaboxer/bloxstrap/files/15166683/Bloxstrap_20240430T145618Z.log)
024-04-30T14:56:18Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-04-30T14:56:18Z [App::OnStartup] Compiled Friday, 3 November 2023 at 9:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-04-30T14:56:18Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-04-30T14:56:18Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240430T145618Z.log
2024-04-30T14:56:18Z [Logger::Initialize] Finished initializing!
2024-04-30T14:56:18Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-04-30T14:56:18Z [JsonManager<Settings>::Load] Loaded successfully!
2024-04-30T14:56:18Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-04-30T14:56:18Z [JsonManager<State>::Load] Loaded successfully!
2024-04-30T14:56:18Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-04-30T14:56:18Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-04-30T14:56:18Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-04-30T14:56:18Z [App::OnStartup] Initializing bootstrapper
2024-04-30T14:56:18Z [App::OnStartup] Initializing bootstrapper dialog
2024-04-30T14:56:19Z [Bootstrapper::Run] Running bootstrapper
2024-04-30T14:56:19Z [Bootstrapper::Run] Performing connectivity check...
2024-04-30T14:56:19Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-04-30T14:56:19Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-30T14:56:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-30T14:56:19Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-04-30T14:56:19Z [Bootstrapper::Run] Connectivity check finished
2024-04-30T14:56:19Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-04-30T14:56:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-04-30T14:56:20Z [Bootstrapper::CheckForUpdates] No updates found
2024-04-30T14:56:20Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-04-30T14:56:20Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-04-30T14:56:20Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-04-30T14:56:20Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-24872f7beace4d0a-rbxPkgManifest.txt
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-24872f7beace4d0a-rbxPkgManifest.txt
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-24872f7beace4d0a-rbxManifest.txt
2024-04-30T14:56:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-24872f7beace4d0a-rbxManifest.txt
2024-04-30T14:56:20Z [Bootstrapper::SetStatus] Upgrading Roblox...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\avatar\...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\configs\...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\fonts\...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\models\...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-04-30T14:56:25Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-04-30T14:56:25Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\sky\...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\sounds\...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-04-30T14:56:26Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-04-30T14:56:26Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\shaders\...
2024-04-30T14:56:26Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-04-30T14:56:26Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-04-30T14:56:27Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-04-30T14:56:27Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ssl\...
2024-04-30T14:56:27Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-04-30T14:56:27Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\textures\...
2024-04-30T14:56:27Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-04-30T14:56:30Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-04-30T14:56:30Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-04-30T14:56:30Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-04-30T14:56:30Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\PlatformContent\pc\textures\...
2024-04-30T14:56:30Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-04-30T14:56:31Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-04-30T14:56:31Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-04-30T14:56:31Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\PlatformContent\pc\terrain\...
2024-04-30T14:56:33Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-04-30T14:56:33Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-04-30T14:56:33Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-04-30T14:56:33Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\PlatformContent\pc\fonts\...
2024-04-30T14:56:33Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-04-30T14:56:33Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-04-30T14:56:33Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ExtraContent\places\...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-04-30T14:56:34Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ExtraContent\LuaPackages\...
2024-04-30T14:56:34Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ExtraContent\translations\...
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-04-30T14:56:34Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-04-30T14:56:35Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-04-30T14:56:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-04-30T14:56:36Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ExtraContent\models\...
2024-04-30T14:56:36Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\ExtraContent\textures\...
2024-04-30T14:56:36Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-04-30T14:56:36Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-04-30T14:56:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-04-30T14:56:37Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-04-30T14:56:39Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-textures2.zip'
2024-04-30T14:56:39Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The file or directory is corrupted and unreadable. : '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\textures\ui\Controls\XboxController\ButtonLB@3x.png')
 ---> System.IO.IOException: The file or directory is corrupted and unreadable. : '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\content\textures\ui\Controls\XboxController\ButtonLB@3x.png'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-04-30T14:56:39Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip

**Comment by pizzaboxer** [comment]
This is an issue relating to something on youe Windows drive. A good first step would be to try and reinstall Bloxstrap, if you can. If you encounter the same error, try manually deleting the folder at `%localappdata%\Bloxstrap` and install it again. If that doesn't work, then try running an SFC scan by opening a Command Prompt window as Administrator and running the `sfc /scannow` command.
