### ISSUE TITLE
An exception occurred while running Bloxstrap (Disk rename problem*)

### ISSUE THREAD

**Issue by EpicRed** [pizzaboxer/bloxstrap#1744]
So i recently renamed my user C: disk and now bloxstrap isnt running cuz its displaying this message i tried all the tips displayed in the wiki but no help  (even clearing temp files*), i think its not recognizing my new user disc name 

The logs are : 
2024-05-04T17:03:05Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-05-04T17:03:05Z [App::OnStartup] Compiled Friday, 3 November 2023 at 10:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-05-04T17:03:05Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir13200_598606427\Bloxstrap-v2.5.4.exe
2024-05-04T17:03:05Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-05-04T17:03:05Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-05-04T17:03:05Z [Logger::Initialize] Initializing at C:\Users\(its displaying my old user disc name * ) 
\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240504T170305Z.log
2024-05-04T17:03:05Z [App::GlobalExceptionHandler] An exception occurred
2024-05-04T17:03:05Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\HashimiDKA\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder
