### ISSUE TITLE
[BUG] An excepction occured while using Bloxstrap

### ISSUE THREAD

**Issue by kotiz1488** [pizzaboxer/bloxstrap#1812]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\petya1337killerXD\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.
As a administrator with full access to every file in my PC, I got this
(infinity configuration)

**Comment by kotiz1488** [comment]
2024-05-15T03:54:00Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-05-15T03:54:00Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 6:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-05-15T03:54:00Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4 (1).exe
2024-05-15T03:54:00Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240515T035400Z.log
2024-05-15T03:54:00Z [Logger::Initialize] Finished initializing!
2024-05-15T03:54:00Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-05-15T03:54:00Z [JsonManager<Settings>::Load] Loaded successfully!
2024-05-15T03:54:00Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-05-15T03:54:00Z [JsonManager<State>::Load] Loaded successfully!
2024-05-15T03:54:00Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-05-15T03:54:00Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-05-15T03:54:00Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-05-15T03:54:00Z [App::OnStartup] Initializing bootstrapper
2024-05-15T03:54:00Z [App::OnStartup] Initializing bootstrapper dialog
2024-05-15T03:54:00Z [Bootstrapper::Run] Running bootstrapper
2024-05-15T03:54:00Z [Bootstrapper::Run] Performing connectivity check...
2024-05-15T03:54:00Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-05-15T03:54:00Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-05-15T03:54:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-05-15T03:54:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-05-15T03:54:01Z [Bootstrapper::Run] Connectivity check finished
2024-05-15T03:54:01Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-05-15T03:54:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-05-15T03:54:02Z [Bootstrapper::CheckForUpdates] No updates found
2024-05-15T03:54:02Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-05-15T03:54:02Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-05-15T03:54:02Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-05-15T03:54:02Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-5e534e6db34e447e-rbxPkgManifest.txt
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-5e534e6db34e447e-rbxPkgManifest.txt
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-5e534e6db34e447e-rbxManifest.txt
2024-05-15T03:54:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-5e534e6db34e447e-rbxManifest.txt
2024-05-15T03:54:03Z [Bootstrapper::SetStatus] Upgrading Roblox...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\avatar\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\configs\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\fonts\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\models\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\sky\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\sounds\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\shaders\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ssl\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\content\textures\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\PlatformContent\pc\textures\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\PlatformContent\pc\terrain\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\PlatformContent\pc\fonts\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ExtraContent\places\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ExtraContent\LuaPackages\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ExtraContent\translations\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ExtraContent\models\...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e\ExtraContent\textures\...
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-5e534e6db34e447e...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-05-15T03:54:03Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-05-15T03:54:03Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-05-15T03:54:04Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-05-15T03:54:04Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-05-15T03:54:04Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-05-15T03:54:04Z [Bootstrapper::RegisterProgramSize] Registered as 564771 KB
2024-05-15T03:54:04Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-05-15T03:54:04Z [App::OnStartup] Bootstrapper task has finished
2024-05-15T03:54:04Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-05-15T03:54:04Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-05-15T03:54:04Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.FastFlagManager.Save()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by kkaran996** [comment]
guide me plss

**Comment by pizzaboxer** [comment]
Sorry for not responding, if you're still having this issue then I've relocated discussion to #2248
