### ISSUE TITLE
[BUG] An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Txkyo03** [pizzaboxer/bloxstrap#1883]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-05-28 175729](https://github.com/pizzaboxer/bloxstrap/assets/171259425/f1c39af2-4ce2-43f7-9d86-cb385e2c6efb)

log contents:
2024-05-30T13:53:48Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-05-30T13:53:48Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 5:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-05-30T13:53:48Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-05-30T13:53:48Z [InstallChecker::FirstTimeRun] Running first-time install
2024-05-30T13:53:48Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240530T135348Z.log
2024-05-30T13:53:48Z [App::GlobalExceptionHandler] An exception occurred
2024-05-30T13:53:48Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Temp\Bloxstrap_20240530T135348Z.log' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.InstallChecker.FirstTimeRun()
   at Bloxstrap.InstallChecker.Check()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Itsyoboymoon** [comment]
method 1# try hit windows logo in keyborad and search disk clean up then uncheck everything expect thumbnails
method 2# try reinstalling bloxstrap if it doesnt work then it may be roblox itself reinstall roblox then try bloxstrap
method 3# try going to c:\Users and type reset and if it said access not allowed allow it and try again

**Comment by Txkyo03** [comment]
where do you exactly type reset?

**Comment by pizzaboxer** [comment]
Can you check to make sure your antivirus isn't interfering?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
