### ISSUE TITLE
[BUG] Unable to launch

### ISSUE THREAD

**Issue by Thedogecraft** [pizzaboxer/bloxstrap#1953]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-06-12T09:06:26Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-06-12T09:06:26Z [App::OnStartup] Compiled Friday, 3 November 2023 at 2:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-06-12T09:06:26Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir15420_1875206754\Bloxstrap-v2.5.4 (1).exe
2024-06-12T09:06:26Z [App::GlobalExceptionHandler] An exception occurred
2024-06-12T09:06:26Z [App::FinalizeExceptionHandling] System.BadImageFormatException: Could not load file or assembly 'System.IO.FileSystem.DriveInfo, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.IO.FileSystem.DriveInfo, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Bloxstrap.InstallChecker.Check()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
Your .NET runtime installation is screwed. Reinstall it: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.31-windows-x64-installer?cid=getdotnetcore
