### ISSUE TITLE
[BUG] cannot enter

### ISSUE THREAD

**Issue by NocreativityTheSecond** [pizzaboxer/bloxstrap#2067]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-06-17T03:46:22Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-17T03:46:22Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 1:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-17T03:46:22Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.6.1.exe
2024-06-17T03:46:22Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-17T03:46:22Z [LaunchSettings::Parse] No launch arguments to parse
2024-06-17T03:46:22Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-17T03:46:22Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-17T03:46:22Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-17T03:46:22Z [JsonManager<State>::Load] Loaded successfully!
2024-06-17T03:46:22Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-17T03:46:22Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-17T03:46:22Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-06-17T03:46:22Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-17T03:46:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-17T03:46:22Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-17T03:46:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-17T03:46:22Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-06-17T03:46:22Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240617T034622Z.log
2024-06-17T03:46:22Z [Logger::Initialize] Finished initializing!
2024-06-17T03:46:22Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-17T03:46:22Z [App::OnStartup] Initializing bootstrapper
2024-06-17T03:46:22Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-17T03:46:22Z [Bootstrapper::Run] Running bootstrapper
2024-06-17T03:46:22Z [Bootstrapper::Run] Performing connectivity check...
2024-06-17T03:46:22Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-17T03:46:22Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-17T03:46:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-17T03:46:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-17T03:46:22Z [Bootstrapper::Run] Connectivity check finished
2024-06-17T03:46:22Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-06-17T03:46:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-06-17T03:46:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-06-17T03:46:23Z [Bootstrapper::CheckForUpdates] No updates found
2024-06-17T03:46:23Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-17T03:46:23Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-06-17T03:46:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-17T03:46:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-17T03:46:23Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-17T03:46:23Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-06-17T03:46:23Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg already exists in the version folder, and is a match
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] ExtraContent\places\Mobile.rbxl already exists in the version folder, and is a match
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowCursor.png already exists in the version folder, and is a match
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowFarCursor.png already exists in the version folder, and is a match
2024-06-17T03:46:23Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-17T03:46:23Z [JsonManager<State>::Save] Save complete!
2024-06-17T03:46:23Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-06-17T03:46:23Z [Bootstrapper::CheckInstall] Checking install
2024-06-17T03:46:23Z [App::OnStartup] Bootstrapper task has finished
2024-06-17T03:46:23Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-17T03:46:23Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-06-17T03:46:23Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Attempted to perform an unauthorized operation.)
 ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValueCore(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   at Bloxstrap.ProtocolHandler.Register(String key, String name, String handler)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by bluepilledgreat** [comment]
Your anti-virus is blocking changes to the registry

**Comment by pizzaboxer** [comment]
^

Check your antivirus to ensure it's not restricting Bloxstrap. You may need to add an exception for it.
