### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cleanbaII** [pizzaboxer/bloxstrap#2111]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

idk i cant update bloxtrap and it just shows dis 
![image](https://github.com/pizzaboxer/bloxstrap/assets/173239522/80e44175-6acc-447e-90ad-10a6697826ee)
 
Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: 67d08563952a2249e3fda87f22344dce

Package has been downloaded to C:\Users\dadadsa\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.

**Comment by cleanbaII** [comment]
2024-06-19T07:04:58Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-19T07:04:58Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 1:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-19T07:04:58Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.6.1 (1).exe
2024-06-19T07:04:58Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-19T07:04:58Z [LaunchSettings::Parse] No launch arguments to parse
2024-06-19T07:04:58Z [InstallChecker::FirstTimeRun] Running first-time install
2024-06-19T07:04:58Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240619T070458Z.log
2024-06-19T07:04:58Z [Logger::Initialize] Finished initializing!
2024-06-19T07:04:58Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-06-19T07:04:58Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-06-19T07:04:58Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\Downloads\ClientSettings\ClientAppSettings.json'.
2024-06-19T07:04:58Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-06-19T07:04:58Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-06-19T07:04:59Z [MainWindow::MainWindow] Initializing menu
2024-06-19T07:05:05Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-19T07:05:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-19T07:05:06Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-19T07:05:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-19T07:05:06Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-06-19T07:05:06Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-19T07:05:06Z [App::OnStartup] Initializing bootstrapper
2024-06-19T07:05:06Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-19T07:05:06Z [Bootstrapper::Run] Running bootstrapper
2024-06-19T07:05:06Z [Bootstrapper::Run] Performing connectivity check...
2024-06-19T07:05:06Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-19T07:05:06Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-19T07:05:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-19T07:05:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-19T07:05:06Z [Bootstrapper::Run] Connectivity check finished
2024-06-19T07:05:06Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-19T07:05:06Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-06-19T07:05:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-19T07:05:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-19T07:05:06Z [Bootstrapper::SetStatus] Installing {product}...
2024-06-19T07:05:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is corrupted (67d08563952a2249e3fda87f22344dce != a84566b04d93520e12bad377fc5e9061)! Deleting and re-downloading...
2024-06-19T07:05:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-06-19T07:05:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T07:05:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T07:05:08Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 6192417 bytes. (1/5)
2024-06-19T07:05:08Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): Указанные данные не могут быть расшифрованы.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-06-19T07:05:08Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-06-19T07:05:08Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T07:05:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T07:05:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 82168835 bytes. (2/5)
2024-06-19T07:05:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: c3dba6f3ae6121bdde8ce0c36e6014fa

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-06-19T07:05:18Z [App::OnStartup] Bootstrapper task has finished
2024-06-19T07:05:18Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-19T07:05:18Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-06-19T07:05:18Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Failed to verify download of http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: c3dba6f3ae6121bdde8ce0c36e6014fa

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.)
 ---> Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: c3dba6f3ae6121bdde8ce0c36e6014fa

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by johnmatthew23idk** [comment]
me to

**Comment by johnmatthew23idk** [comment]
2024-06-19T08:28:39Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-19T08:28:39Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 6:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-19T08:28:39Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-06-19T08:28:39Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-19T08:28:39Z [LaunchSettings::Parse] No launch arguments to parse
2024-06-19T08:28:39Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-19T08:28:39Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-19T08:28:39Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-19T08:28:39Z [JsonManager<State>::Load] Loaded successfully!
2024-06-19T08:28:39Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-19T08:28:39Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-19T08:28:39Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-06-19T08:28:39Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-19T08:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-19T08:28:39Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-19T08:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-19T08:28:39Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-06-19T08:28:39Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240619T082839Z.log
2024-06-19T08:28:39Z [Logger::Initialize] Finished initializing!
2024-06-19T08:28:39Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-19T08:28:39Z [App::OnStartup] Initializing bootstrapper
2024-06-19T08:28:39Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-19T08:28:39Z [Bootstrapper::Run] Running bootstrapper
2024-06-19T08:28:39Z [Bootstrapper::Run] Performing connectivity check...
2024-06-19T08:28:39Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-19T08:28:39Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-19T08:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-19T08:28:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-19T08:28:40Z [Bootstrapper::Run] Connectivity check finished
2024-06-19T08:28:40Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-06-19T08:28:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-06-19T08:28:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-06-19T08:28:40Z [Bootstrapper::CheckForUpdates] No updates found
2024-06-19T08:28:40Z [RobloxDeployment::GetInfo] Getting deploy info for channel zflag (extraInformation=False)
2024-06-19T08:28:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-06-19T08:28:41Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-19T08:28:41Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-06-19T08:28:41Z [RobloxFastFlags::Fetch.PCClientBootstrapper.zflag] Fetching fast flags
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-rbxPkgManifest.txt
2024-06-19T08:28:41Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-06-19T08:28:41Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is corrupted (91037b10171d31c44860de8954deefdd != a84566b04d93520e12bad377fc5e9061)! Deleting and re-downloading...
2024-06-19T08:28:41Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T08:28:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T08:28:56Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 52051233 bytes. (1/5)
2024-06-19T08:28:56Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-06-19T08:28:56Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-06-19T08:28:56Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T08:28:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip
2024-06-19T08:29:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 82168835 bytes. (2/5)
2024-06-19T08:29:18Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: 2020a0657abfe9961685bffd821a9d96

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-06-19T08:29:18Z [App::OnStartup] Bootstrapper task has finished
2024-06-19T08:29:18Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-19T08:29:18Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-06-19T08:29:18Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Failed to verify download of http://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: 2020a0657abfe9961685bffd821a9d96

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.)
 ---> Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/channel/common/version-2cca5ed32b534b2a-RobloxApp.zip

Got signature: 2020a0657abfe9961685bffd821a9d96

Package has been downloaded to %UserProfile%\AppData\Local\Bloxstrap\Downloads\a84566b04d93520e12bad377fc5e9061

Please send the file shown above in a bug report.
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
2024-06-19T08:29:33Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
2024-06-19T08:29:33Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-19T08:29:33Z [JsonManager<Settings>::Save] Save complete!
2024-06-19T08:29:33Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-19T08:29:33Z [JsonManager<State>::Save] Save complete!

**Comment by pizzaboxer** [comment]
Addressed in Wiki
