### ISSUE TITLE
[BUG] Bloxstrap uninstallation access is denied

### ISSUE THREAD

**Issue by shotgunn87** [pizzaboxer/bloxstrap#2135]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-06-21T09:11:57Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-21T09:11:57Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 6:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-21T09:11:57Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-06-21T09:11:57Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-21T09:11:57Z [LaunchSettings::Parse] Parsing launch flags
2024-06-21T09:11:57Z [LaunchSettings::ParseFlag] Started with IsUninstall flag
2024-06-21T09:11:57Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-21T09:11:57Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-21T09:11:57Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-21T09:11:57Z [JsonManager<State>::Load] Loaded successfully!
2024-06-21T09:11:57Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-21T09:11:57Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-21T09:11:57Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-06-21T09:11:57Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-21T09:11:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-21T09:11:57Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-21T09:11:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-21T09:11:58Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-06-21T09:11:58Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240621T091158Z.log
2024-06-21T09:11:58Z [App::GlobalExceptionHandler] An exception occurred
2024-06-21T09:11:58Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Temp\Bloxstrap_20240621T091158Z.log' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
You may have to uninstall it manually, which you can do by deleting the `%localappdata%\Bloxstrap` folder, and opening the Registry editor to delete the `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap` key.

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
