### ISSUE TITLE
[BUG] Help me bloxstrap won't start

### ISSUE THREAD

**Issue by NooCruuupt** [pizzaboxer/bloxstrap#2169]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Bloxstrap-v2 6 1_ZGrcdmjDlC](https://github.com/pizzaboxer/bloxstrap/assets/173799746/ad56a0b7-332d-48c1-8ba0-23921fc89762)

![RobloxPlayerBeta_unrlW9a0cS](https://github.com/pizzaboxer/bloxstrap/assets/173799746/3e229c54-cbb7-43bc-8de8-25455d6bc4f6)

[Bloxstrap_20240625T113934Z.log](https://github.com/user-attachments/files/15970800/Bloxstrap_20240625T113934Z.log)

LOG FILE

```
2024-06-25T11:39:34Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-25T11:39:34Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 1:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-25T11:39:34Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir6444_1669593736\Bloxstrap-v2.6.1.exe
2024-06-25T11:39:34Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-25T11:39:34Z [LaunchSettings::Parse] No launch arguments to parse
2024-06-25T11:39:34Z [InstallChecker::FirstTimeRun] Running first-time install
2024-06-25T11:39:34Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240625T113934Z.log
2024-06-25T11:39:34Z [Logger::Initialize] Finished initializing!
2024-06-25T11:39:34Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-06-25T11:39:34Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-06-25T11:39:34Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Temp\scoped_dir6444_1669593736\ClientSettings\ClientAppSettings.json'.
2024-06-25T11:39:34Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-06-25T11:39:34Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-06-25T11:39:34Z [MainWindow::MainWindow] Initializing menu
2024-06-25T11:39:58Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '60' is pending
2024-06-25T11:40:04Z [FastFlagManager::SetValue] Setting of 'FFlagFixGraphicsQuality' to 'True' is pending
2024-06-25T11:40:14Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-25T11:40:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-25T11:40:14Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-25T11:40:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-25T11:40:14Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-06-25T11:40:14Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-25T11:40:14Z [App::OnStartup] Initializing bootstrapper
2024-06-25T11:40:14Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-25T11:40:14Z [Bootstrapper::Run] Running bootstrapper
2024-06-25T11:40:14Z [Bootstrapper::Run] Performing connectivity check...
2024-06-25T11:40:14Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-25T11:40:14Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-25T11:40:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-25T11:40:44Z [RobloxDeployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-06-25T11:40:44Z [RobloxDeployment::GetInfo] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.GetInfo(String channel, Boolean extraInformation, String binaryType)
2024-06-25T11:40:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-25T11:40:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-25T11:40:45Z [Bootstrapper::Run] Connectivity check finished
2024-06-25T11:40:45Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-25T11:40:45Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-06-25T11:40:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-rbxPkgManifest.txt
2024-06-25T11:40:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-rbxPkgManifest.txt
2024-06-25T11:40:45Z [Bootstrapper::SetStatus] Installing {product}...
2024-06-25T11:40:45Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-06-25T11:40:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip
2024-06-25T11:40:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (81896392 bytes total)
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-avatar.zip
2024-06-25T11:40:52Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-avatar.zip
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (405085 bytes total)
2024-06-25T11:40:52Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-configs.zip
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-configs.zip
2024-06-25T11:40:52Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (228207 bytes total)
2024-06-25T11:40:52Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-06-25T11:40:52Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-fonts.zip
2024-06-25T11:40:52Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-06-25T11:40:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-fonts.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6780428 bytes total)
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-models.zip
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-models.zip
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-sky.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-sky.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-sounds.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-sounds.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-06-25T11:40:53Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-shaders.zip
2024-06-25T11:40:53Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-06-25T11:40:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-shaders.zip
2024-06-25T11:40:54Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9309023 bytes total)
2024-06-25T11:40:54Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-06-25T11:40:54Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-06-25T11:40:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-ssl.zip
2024-06-25T11:40:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-ssl.zip
2024-06-25T11:40:54Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (133126 bytes total)
2024-06-25T11:40:54Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-06-25T11:40:54Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-06-25T11:40:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-textures2.zip
2024-06-25T11:40:54Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-06-25T11:40:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-textures2.zip
2024-06-25T11:40:54Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-06-25T11:40:55Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (9712485 bytes total)
2024-06-25T11:40:55Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-06-25T11:40:55Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-06-25T11:40:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-textures3.zip
2024-06-25T11:40:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-textures3.zip
2024-06-25T11:40:56Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-06-25T11:40:56Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-06-25T11:40:56Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-06-25T11:40:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-terrain.zip
2024-06-25T11:40:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-terrain.zip
2024-06-25T11:40:56Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-06-25T11:40:56Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-06-25T11:40:56Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-06-25T11:40:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-platform-fonts.zip
2024-06-25T11:40:56Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-06-25T11:40:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-content-platform-fonts.zip
2024-06-25T11:40:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-06-25T11:40:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-06-25T11:40:57Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-06-25T11:40:57Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-06-25T11:40:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-places.zip
2024-06-25T11:40:57Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-06-25T11:40:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-places.zip
2024-06-25T11:40:57Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1041610 bytes total)
2024-06-25T11:40:57Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-06-25T11:40:57Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-06-25T11:40:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-luapackages.zip
2024-06-25T11:40:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-06-25T11:40:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-luapackages.zip
2024-06-25T11:40:57Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-06-25T11:40:58Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9268066 bytes total)
2024-06-25T11:40:58Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-06-25T11:40:58Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-06-25T11:40:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-translations.zip
2024-06-25T11:40:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-translations.zip
2024-06-25T11:40:58Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (398086 bytes total)
2024-06-25T11:40:58Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-06-25T11:40:58Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-06-25T11:40:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-models.zip
2024-06-25T11:40:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-models.zip
2024-06-25T11:40:58Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-06-25T11:40:58Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-06-25T11:40:59Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (9155458 bytes total)
2024-06-25T11:40:59Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-06-25T11:40:59Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-06-25T11:40:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-textures.zip
2024-06-25T11:40:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-extracontent-textures.zip
2024-06-25T11:40:59Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-06-25T11:41:00Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (14122523 bytes total)
2024-06-25T11:41:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-06-25T11:41:00Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-06-25T11:41:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-WebView2.zip
2024-06-25T11:41:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-WebView2.zip
2024-06-25T11:41:00Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-06-25T11:41:00Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-06-25T11:41:00Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-06-25T11:41:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-WebView2RuntimeInstaller.zip
2024-06-25T11:41:00Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-06-25T11:41:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6b63ea89d2e54fd7-WebView2RuntimeInstaller.zip
2024-06-25T11:41:00Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-06-25T11:41:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-06-25T11:41:01Z [Bootstrapper::SetStatus] Configuring {product}...
2024-06-25T11:41:01Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-06-25T11:41:01Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-25T11:41:01Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-06-25T11:41:01Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-06-25T11:41:01Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-06-25T11:41:01Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-06-25T11:41:01Z [Bootstrapper::CheckModPreset.Sounds.OldDeath.ogg] Writing 'content\sounds\ouch.ogg' as preset is enabled, and mod file does not exist or does not match preset
2024-06-25T11:41:01Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-06-25T11:41:01Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-06-25T11:41:01Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-25T11:41:01Z [JsonManager<State>::Save] Save complete!
2024-06-25T11:41:01Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-06-25T11:41:01Z [Bootstrapper::Register] Registered application
2024-06-25T11:41:01Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-06-25T11:41:01Z [Bootstrapper::RegisterProgramSize] Registered as 430928 KB
2024-06-25T11:41:01Z [Bootstrapper::CheckInstall] Checking install
2024-06-25T11:41:01Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-25T11:41:01Z [JsonManager<Settings>::Save] Save complete!
2024-06-25T11:41:01Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-25T11:41:01Z [JsonManager<State>::Save] Save complete!
2024-06-25T11:41:01Z [Bootstrapper::SetStatus] Starting {product}...
2024-06-25T11:41:01Z [Bootstrapper::StartRoblox] Started Roblox (PID 2324)
2024-06-25T11:41:04Z [NotifyIconWrapper::InitializeContextMenu] Initializing context menu
2024-06-25T11:41:04Z [ActivityWatcher::StartWatcher] Opening Roblox log file...
2024-06-25T11:41:04Z [ActivityWatcher::StartWatcher] Opened %UserProfile%\AppData\Local\Roblox\logs\0.630.0.6300556_20240625T114103Z_Player_293C2_last.log
2024-06-25T11:41:04Z [Bootstrapper::StartRoblox] Waiting for Roblox to close
2024-06-25T11:54:56Z [Bootstrapper::StartRoblox] Roblox has exited
2024-06-25T11:54:56Z [App::OnStartup] Bootstrapper task has finished
2024-06-25T11:54:56Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-25T11:54:56Z [MenuContainer::Window_Closed] Context menu container closed
2024-06-25T11:54:56Z [App::GlobalExceptionHandler] An exception occurred
2024-06-25T11:54:56Z [App::FinalizeExceptionHandling] System.ArgumentException: Process with an Id of 2324 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at Bloxstrap.UI.Elements.ContextMenu.MenuContainer.CloseRobloxMenuItem_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NooCruuupt** [comment]
HELP ME PLEASE!

**Comment by pizzaboxer** [comment]
Problem is not related to Bloxstrap. This is with Roblox itself failing to connect.
