### ISSUE TITLE
[BUG] from bloxstrap

### ISSUE THREAD

**Issue by olimaviw** [pizzaboxer/bloxstrap#2176]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im doing dup the roblox the error its here and http into http404 do fix again here this code error2024-06-26T07:50:00Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-06-26T07:50:00Z [App::OnStartup] Compiled Wednesday, 11 October 2023 at 8:29:04 PM from commit a099d160726f4d5ac832f97a8e167ae0338193ad (tag/v2.5.3)
2024-06-26T07:50:00Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-06-26T07:50:00Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240626T075000Z.log
2024-06-26T07:50:00Z [Logger::Initialize] Finished initializing!
2024-06-26T07:50:00Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-26T07:50:00Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-26T07:50:00Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-26T07:50:00Z [JsonManager<State>::Load] Loaded successfully!
2024-06-26T07:50:00Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-26T07:50:00Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-26T07:50:00Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-06-26T07:50:00Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-26T07:50:00Z [App::OnStartup] Initializing bootstrapper
2024-06-26T07:50:00Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-26T07:50:00Z [App::OnStartup] Creating singleton mutex
2024-06-26T07:50:00Z [App::OnStartup] Warning - singleton mutex already exists!
2024-06-26T07:50:00Z [Bootstrapper::Run] Running bootstrapper
2024-06-26T07:50:00Z [Bootstrapper::Run] Performing connectivity check...
2024-06-26T07:50:00Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-26T07:50:00Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-26T07:50:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-26T07:50:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-26T07:50:01Z [Bootstrapper::Run] Connectivity check finished
2024-06-26T07:50:01Z [RobloxDeployment::GetInfo] Getting deploy info for channel zlive (extraInformation=False)
2024-06-26T07:50:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive
2024-06-26T07:50:01Z [HttpClientLoggingHandler::ProcessResponse] 401 Unauthorized https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive
2024-06-26T07:50:01Z [RobloxDeployment::GetInfo] Failed to fetch deploy info!
	Status code: Unauthorized
	Response: {"errors":[{"code":5,"message":"Not authorized to perform this action."}]}
2024-06-26T07:50:01Z [App::OnStartup] Bootstrapper task has finished
2024-06-26T07:50:01Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-26T07:50:02Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-06-26T07:50:02Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized))
 ---> Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)
   at Bloxstrap.RobloxDeployment.GetInfo(String channel, Boolean extraInformation)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
You're on an outdated version. [Download the latest version.](https://github.com/pizzaboxer/bloxstrap/releases/latest)
