### ISSUE TITLE
Bloxtrap exception[BUG] 

### ISSUE THREAD

**Issue by MOSTROVERDE** [pizzaboxer/bloxstrap#2196]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-06-28T21:11:53Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-06-28T21:11:53Z [App::OnStartup] Compiled Friday, 3 November 2023 at 3:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-06-28T21:11:53Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-06-28T21:11:53Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240628T211153Z.log
2024-06-28T21:11:53Z [Logger::Initialize] Finished initializing!
2024-06-28T21:11:53Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20240621T165939Z.log'
2024-06-28T21:11:53Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-28T21:11:53Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-28T21:11:53Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-28T21:11:53Z [JsonManager<State>::Load] Loaded successfully!
2024-06-28T21:11:53Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-28T21:11:53Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-28T21:11:53Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-06-28T21:11:53Z [App::OnStartup] Initializing bootstrapper
2024-06-28T21:11:53Z [App::OnStartup] Initializing bootstrapper dialog
2024-06-28T21:11:53Z [App::OnStartup] Creating singleton mutex
2024-06-28T21:11:53Z [Bootstrapper::Run] Running bootstrapper
2024-06-28T21:11:53Z [Bootstrapper::Run] Performing connectivity check...
2024-06-28T21:11:53Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-06-28T21:11:53Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-28T21:11:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-28T21:11:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-06-28T21:11:54Z [Bootstrapper::Run] Connectivity check finished
2024-06-28T21:11:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel zperfverify (extraInformation=False)
2024-06-28T21:11:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zperfverify
2024-06-28T21:11:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zperfverify
2024-06-28T21:11:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-06-28T21:11:54Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-06-28T21:11:54Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-06-28T21:11:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-28T21:11:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-06-28T21:11:55Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-06-28T21:11:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/zperfverify/version-4ae71dfc71854fa7-rbxPkgManifest.txt
2024-06-28T21:11:55Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/zperfverify/version-4ae71dfc71854fa7-rbxPkgManifest.txt
2024-06-28T21:11:55Z [App::OnStartup] Bootstrapper task has finished
2024-06-28T21:11:55Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-06-28T21:11:55Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-06-28T21:11:55Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
Addressed in Wiki
