### ISSUE TITLE
[BUG] Roblox didn't start

### ISSUE THREAD

**Issue by rthyjk** [pizzaboxer/bloxstrap#2208]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2024-06-30T05:29:02Z [App::OnStartup] Starting Bloxstrap v2.6.1
2024-06-30T05:29:02Z [App::OnStartup] Compiled Saturday, 15 June 2024 at 5:59:07 AM from commit b84522a643f254eb4cbaecbed43afd7de03198aa (tag/v2.6.1)
2024-06-30T05:29:02Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-06-30T05:29:05Z [LaunchSettings::Parse] Parsing launch arguments
2024-06-30T05:29:05Z [LaunchSettings::Parse] No launch arguments to parse
2024-06-30T05:29:05Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-06-30T05:29:05Z [JsonManager<Settings>::Load] Loaded successfully!
2024-06-30T05:29:05Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-06-30T05:29:05Z [JsonManager<State>::Load] Loaded successfully!
2024-06-30T05:29:05Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-06-30T05:29:05Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-06-30T05:29:05Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-06-30T05:29:05Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-06-30T05:29:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-06-30T05:29:12Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-06-30T05:29:15Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] Connecting...
2024-06-30T05:29:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version
2024-06-30T05:29:15Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] Connecting...
2024-06-30T05:29:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version
2024-06-30T05:29:17Z [RobloxDeployment::TestConnection.https://s3.amazonaws.com/setup.roblox.com] Connecting...
2024-06-30T05:29:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://s3.amazonaws.com/setup.roblox.com/version
2024-06-30T05:29:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/version
2024-06-30T05:29:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://s3.amazonaws.com/setup.roblox.com/version
2024-06-30T05:29:53Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-06-30T05:29:53Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-06-30T05:29:53Z [App::GlobalExceptionHandler] An exception occurred
2024-06-30T05:29:54Z [App::FinalizeExceptionHandling] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
   at Bloxstrap.RobloxDeployment.InitializeConnectivity()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
Check your antivirus to ensure it isn''t preventing Bloxstrap from connecting to the internet.
