### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\Blade Skilled\AppData\Local\Bloxstrap\Logs' is denied.

### ISSUE THREAD

**Issue by bladeclickers** [pizzaboxer/bloxstrap#2254]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap is trying to install to an non-existent user (my user doesn't have a space) therefore i cant use it.
There is a page on the wiki about this, but it keeps creating a new user folder that doesnt exist.

2024-07-06T10:24:22Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-07-06T10:24:23Z [App::OnStartup] Compiled Wednesday, 19 June 2024 at 2:39:08 AM from DESKTOP-FGF6DO8\User
2024-07-06T10:24:23Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-07-06T10:24:23Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-07-06T10:24:23Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-07-06T10:24:23Z [Logger::Initialize] Initializing at C:\Users\Blade Skilled\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240706T102423Z.log
2024-07-06T10:24:23Z [App::GlobalExceptionHandler] An exception occurred
2024-07-06T10:24:23Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\Blade Skilled\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
> There is a page on the wiki about this, but it keeps creating a new user folder that doesnt exist.

Then specify a folder that does exist.
