### ISSUE TITLE
Task Canceled Exception

### ISSUE THREAD

**Issue by omulus64** [pizzaboxer/bloxstrap#2294]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I do not know how or why this issue occurred, it has not happened before. I don't know what this log means but I hope it can be fixed. Hopefully no one else has had this issue, and tell me if there is already a workaround. Anyways thank you! And for now I'll just be using the regular Roblox player.

2024-07-09T21:31:25Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-07-09T21:31:25Z [App::OnStartup] Compiled Wednesday, 10 July 2024 at 4:03:19 AM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-07-09T21:31:25Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\Bloxstrap-v2.7.0.exe
2024-07-09T21:31:25Z [LaunchSettings::Parse] Parsing launch arguments
2024-07-09T21:31:25Z [LaunchSettings::Parse] No launch arguments to parse
2024-07-09T21:31:25Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-07-09T21:31:25Z [JsonManager<Settings>::Load] Loaded successfully!
2024-07-09T21:31:25Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-09T21:31:25Z [JsonManager<State>::Load] Loaded successfully!
2024-07-09T21:31:25Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-09T21:31:25Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-07-09T21:31:25Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-07-09T21:31:25Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-07-09T21:31:25Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-09T21:31:25Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-07-09T21:31:27Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] Connecting...
2024-07-09T21:31:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version
2024-07-09T21:31:27Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] Connecting...
2024-07-09T21:31:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version
2024-07-09T21:31:29Z [RobloxDeployment::TestConnection.https://s3.amazonaws.com/setup.roblox.com] Connecting...
2024-07-09T21:31:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://s3.amazonaws.com/setup.roblox.com/version
2024-07-09T21:31:55Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-09T21:31:55Z [App::GlobalExceptionHandler] An exception occurred
2024-07-09T21:31:55Z [App::FinalizeExceptionHandling] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
   at Bloxstrap.RobloxDeployment.InitializeConnectivity()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-07-09T21:31:57Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-09T21:31:57Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-09T21:31:59Z [RobloxDeployment::TestConnection.https://s3.amazonaws.com/setup.roblox.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)

**Comment by realeagleFR** [comment]
I'm still having this issue, I'm super confused

**Comment by pizzaboxer** [comment]
I thought I had fixed the wrong error message displaying for this, I guess not.

Anyway, this is a problem with your internet connection. Check to make sure your antivirus isn't preventing Bloxstrap from connecting to the internet.

**Comment by omulus64** [comment]
Thanks!

From: pizzaboxer ***@***.***>
Date: Wednesday, 16 October 2024 at 9:08 pm
To: bloxstraplabs/bloxstrap ***@***.***>
Cc: Ethan Paget ***@***.***>, Author ***@***.***>
Subject: Re: [bloxstraplabs/bloxstrap] Task Canceled Exception (FIXED IN LATEST VERSION) (Issue #2294)
Caution: This is an external email sent from outside of Caulfield Grammar School. Do not click links or open attachments unless you trust the sender and content. When in doubt, contact the IT Service Desk ***@***.******@***.***>.


Closed #2294<https://github.com/bloxstraplabs/bloxstrap/issues/2294> as completed.
