### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by 361m** [pizzaboxer/bloxstrap#2334]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

```
2024-07-12T15:28:39Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-07-12T15:28:39Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 7:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-07-12T15:28:39Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-07-12T15:28:39Z [LaunchSettings::Parse] Parsing launch arguments
2024-07-12T15:28:39Z [LaunchSettings::Parse] No launch arguments to parse
2024-07-12T15:28:39Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-07-12T15:28:39Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-07-12T15:28:39Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-07-12T15:28:39Z [JsonManager<Settings>::Load] Failed to load!
2024-07-12T15:28:39Z [JsonManager<Settings>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Settings.json'.
2024-07-12T15:28:39Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-12T15:28:39Z [JsonManager<State>::Load] Failed to load!
2024-07-12T15:28:39Z [JsonManager<State>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\State.json'.
2024-07-12T15:28:39Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-12T15:28:39Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-07-12T15:28:39Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
2024-07-12T15:28:39Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-07-12T15:28:39Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-07-12T15:28:39Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-12T15:28:39Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-07-12T15:28:39Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-07-12T15:28:39Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240712T152839Z.log
2024-07-12T15:28:39Z [Logger::Initialize] Finished initializing!
2024-07-12T15:28:39Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-07-12T15:28:39Z [App::OnStartup] Initializing bootstrapper
2024-07-12T15:28:39Z [App::OnStartup] Initializing bootstrapper dialog
2024-07-12T15:28:39Z [Bootstrapper::Run] Running bootstrapper
2024-07-12T15:28:39Z [Bootstrapper::Run] Performing connectivity check...
2024-07-12T15:28:39Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-07-12T15:28:39Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-12T15:28:39Z [Bootstrapper::Run] Connectivity check finished
2024-07-12T15:28:39Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-07-12T15:28:39Z [Bootstrapper::CheckForUpdates] No updates found
2024-07-12T15:28:39Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-12T15:28:39Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-rbxPkgManifest.txt
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-rbxPkgManifest.txt
2024-07-12T15:28:39Z [Bootstrapper::SetStatus] Installing {product}...
2024-07-12T15:28:39Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-RobloxApp.zip
2024-07-12T15:28:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-RobloxApp.zip
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (82412512 bytes total)
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-avatar.zip
2024-07-12T15:29:07Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-avatar.zip
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-07-12T15:29:07Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-configs.zip
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-configs.zip
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (235542 bytes total)
2024-07-12T15:29:07Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-07-12T15:29:07Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-fonts.zip
2024-07-12T15:29:07Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-07-12T15:29:07Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-07-12T15:29:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-fonts.zip
2024-07-12T15:29:08Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-07-12T15:29:09Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-07-12T15:29:09Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-07-12T15:29:09Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-07-12T15:29:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-models.zip
2024-07-12T15:29:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-models.zip
2024-07-12T15:29:09Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-07-12T15:29:09Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-07-12T15:29:09Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-07-12T15:29:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-sky.zip
2024-07-12T15:29:09Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-07-12T15:29:09Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-07-12T15:29:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-sky.zip
2024-07-12T15:29:10Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-07-12T15:29:10Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-07-12T15:29:10Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-07-12T15:29:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-sounds.zip
2024-07-12T15:29:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-sounds.zip
2024-07-12T15:29:10Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-07-12T15:29:10Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-07-12T15:29:10Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-07-12T15:29:10Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-07-12T15:29:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-shaders.zip
2024-07-12T15:29:10Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-07-12T15:29:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-shaders.zip
2024-07-12T15:29:13Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (10003504 bytes total)
2024-07-12T15:29:13Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-07-12T15:29:13Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-07-12T15:29:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-ssl.zip
2024-07-12T15:29:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-ssl.zip
2024-07-12T15:29:13Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (133126 bytes total)
2024-07-12T15:29:13Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-07-12T15:29:13Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-07-12T15:29:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-textures2.zip
2024-07-12T15:29:13Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-07-12T15:29:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-textures2.zip
2024-07-12T15:29:14Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-07-12T15:29:16Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (10018802 bytes total)
2024-07-12T15:29:16Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-07-12T15:29:16Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-07-12T15:29:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-textures3.zip
2024-07-12T15:29:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-textures3.zip
2024-07-12T15:29:17Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-07-12T15:29:18Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-07-12T15:29:18Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-07-12T15:29:18Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-07-12T15:29:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-terrain.zip
2024-07-12T15:29:18Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-07-12T15:29:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-terrain.zip
2024-07-12T15:29:18Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-07-12T15:29:18Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-07-12T15:29:18Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-07-12T15:29:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-content-platform-fonts.zip
2024-07-12T15:29:18Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-07-12T15:29:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-content-platform-fonts.zip
2024-07-12T15:29:24Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-07-12T15:29:24Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-07-12T15:29:24Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-07-12T15:29:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-places.zip
2024-07-12T15:29:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-places.zip
2024-07-12T15:29:24Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1042079 bytes total)
2024-07-12T15:29:24Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-07-12T15:29:24Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-07-12T15:29:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-luapackages.zip
2024-07-12T15:29:24Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-07-12T15:29:24Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-07-12T15:29:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-luapackages.zip
2024-07-12T15:29:27Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9333337 bytes total)
2024-07-12T15:29:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-07-12T15:29:27Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-07-12T15:29:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-translations.zip
2024-07-12T15:29:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-translations.zip
2024-07-12T15:29:27Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (411280 bytes total)
2024-07-12T15:29:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-07-12T15:29:27Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-07-12T15:29:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-models.zip
2024-07-12T15:29:27Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-07-12T15:29:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-models.zip
2024-07-12T15:29:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-07-12T15:29:30Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (9131756 bytes total)
2024-07-12T15:29:30Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-07-12T15:29:30Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-07-12T15:29:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-textures.zip
2024-07-12T15:29:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-extracontent-textures.zip
2024-07-12T15:29:30Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-07-12T15:29:34Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (14122523 bytes total)
2024-07-12T15:29:34Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-07-12T15:29:34Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-07-12T15:29:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-WebView2.zip
2024-07-12T15:29:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-WebView2.zip
2024-07-12T15:29:35Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-07-12T15:29:35Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-07-12T15:29:35Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-07-12T15:29:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-3243b6d003cf4642-WebView2RuntimeInstaller.zip
2024-07-12T15:29:35Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-07-12T15:29:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-3243b6d003cf4642-WebView2RuntimeInstaller.zip
2024-07-12T15:29:35Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-07-12T15:29:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-07-12T15:29:36Z [Bootstrapper::SetStatus] Configuring {product}...
2024-07-12T15:29:36Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-07-12T15:29:36Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-07-12T15:29:36Z [Bootstrapper::RegisterProgramSize] Registered as 435593 KB
2024-07-12T15:29:36Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-12T15:29:36Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-07-12T15:29:36Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-07-12T15:29:36Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-07-12T15:29:36Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-07-12T15:29:36Z [Bootstrapper::CheckModPreset.Sounds.OldDeath.ogg] Writing 'content\sounds\ouch.ogg' as preset is enabled, and mod file does not exist or does not match preset
2024-07-12T15:29:36Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-07-12T15:29:36Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-07-12T15:29:36Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-12T15:29:36Z [JsonManager<State>::Save] Save complete!
2024-07-12T15:29:36Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-07-12T15:29:36Z [Bootstrapper::CheckInstall] Checking install
2024-07-12T15:29:36Z [App::OnStartup] Bootstrapper task has finished
2024-07-12T15:29:36Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-07-12T15:29:36Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-07-12T15:29:36Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Attempted to perform an unauthorized operation.)
 ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValueCore(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   at Bloxstrap.ProtocolHandler.Register(String key, String name, String handler)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   ```
![image_2024-07-12_163435162](https://github.com/user-attachments/assets/25002021-11e7-49ac-bc73-ad0627191d06)

**Comment by pizzaboxer** [comment]
Antivirus issue. Check to make sure it isn't restricting Bloxstrap from doing anything (since it's unable to write to the registry). You may need to add an exception for it.
