### ISSUE TITLE
An exception occurred while running Bloxstrap[BUG] 

### ISSUE THREAD

**Issue by Pieower** [pizzaboxer/bloxstrap#2385]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-07-16T05:15:44Z [App::OnStartup] Starting Bloxstrap v2.5.2
2024-07-16T05:15:44Z [App::OnStartup] Compiled Sunday, 27 August 2023 at 3:42:51 AM from commit 197429dbf936b791d0472f474c0eb9349eb6f0ed (tag/v2.5.2)
2024-07-16T05:15:44Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-07-16T05:15:44Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240716T051544Z.log
2024-07-16T05:15:44Z [Logger::Initialize] Finished initializing!
2024-07-16T05:15:44Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-07-16T05:15:44Z [JsonManager<Settings>::Load] Loaded successfully!
2024-07-16T05:15:44Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-16T05:15:44Z [JsonManager<State>::Load] Loaded successfully!
2024-07-16T05:15:44Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-16T05:15:44Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-07-16T05:15:44Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-07-16T05:15:44Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-07-16T05:15:44Z [Protocol::ParseUri] Changed Roblox channel from LIVE to zsatinttest633
2024-07-16T05:15:44Z [JsonManager<State>::Save] Save request ignored
2024-07-16T05:15:44Z [App::OnStartup] Initializing bootstrapper
2024-07-16T05:15:44Z [App::OnStartup] Initializing bootstrapper dialog
2024-07-16T05:15:44Z [App::OnStartup] Creating singleton mutex
2024-07-16T05:15:44Z [Bootstrapper::Run] Running bootstrapper
2024-07-16T05:15:44Z [Bootstrapper::Run] Performing connectivity check...
2024-07-16T05:15:44Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-07-16T05:15:44Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-16T05:15:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-16T05:15:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-16T05:15:44Z [Bootstrapper::Run] Connectivity check finished
2024-07-16T05:15:44Z [RobloxDeployment::GetInfo] Getting deploy info for channel zsatinttest633 (extraInformation=False)
2024-07-16T05:15:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zsatinttest633
2024-07-16T05:15:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zsatinttest633
2024-07-16T05:15:44Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-16T05:15:44Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-07-16T05:15:44Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-07-16T05:15:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-16T05:15:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-07-16T05:15:45Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-07-16T05:15:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/zsatinttest633/version-b3034c3205bf4af4-rbxPkgManifest.txt
2024-07-16T05:15:45Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/zsatinttest633/version-b3034c3205bf4af4-rbxPkgManifest.txt
2024-07-16T05:15:45Z [App::OnStartup] Bootstrapper task has finished
2024-07-16T05:15:45Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-07-16T05:15:45Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-07-16T05:15:45Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by BokBoy** [comment]
"Update to the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest"
-> Pizzaboxer, many times before
