### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Gxmrrah** [pizzaboxer/bloxstrap#2422]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So recently I changed the name of my user folder and now when I try to install bloxstrap it wont work even though I deleted all the files in local app data and restarted pc.
![Screenshot 2024-07-18 125821](https://github.com/user-attachments/assets/92996d49-a618-48ca-b284-b98e114316d4)

Here is the log contents:
2024-07-18T16:54:23Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-07-18T16:54:23Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 2:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-07-18T16:54:23Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-07-18T16:54:23Z [LaunchSettings::Parse] Parsing launch arguments
2024-07-18T16:54:23Z [LaunchSettings::Parse] No launch arguments to parse
2024-07-18T16:54:23Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-07-18T16:54:23Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-07-18T16:54:23Z [JsonManager<Settings>::Load] Loading from C:\Users\Itstj\AppData\Local\Bloxstrap\Settings.json...
2024-07-18T16:54:23Z [JsonManager<Settings>::Load] Failed to load!
2024-07-18T16:54:23Z [JsonManager<Settings>::Load] Could not find a part of the path 'C:\Users\Itstj\AppData\Local\Bloxstrap\Settings.json'.
2024-07-18T16:54:23Z [JsonManager<State>::Load] Loading from C:\Users\Itstj\AppData\Local\Bloxstrap\State.json...
2024-07-18T16:54:23Z [JsonManager<State>::Load] Failed to load!
2024-07-18T16:54:23Z [JsonManager<State>::Load] Could not find a part of the path 'C:\Users\Itstj\AppData\Local\Bloxstrap\State.json'.
2024-07-18T16:54:23Z [JsonManager<Dictionary`2>::Load] Loading from C:\Users\Itstj\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-18T16:54:23Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-07-18T16:54:23Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Users\Itstj\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
2024-07-18T16:54:23Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-07-18T16:54:23Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-07-18T16:54:23Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-07-18T16:54:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-18T16:54:23Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-07-18T16:54:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-07-18T16:54:23Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-07-18T16:54:23Z [Logger::Initialize] Initializing at C:\Users\Itstj\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240718T165423Z.log
2024-07-18T16:54:23Z [App::GlobalExceptionHandler] An exception occurred
2024-07-18T16:54:23Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\Itstj\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by toofastforboo** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

**Comment by Gxmrrah** [comment]
> > * [x]  My answer given in the checkbox above is a lie.
> >   https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

Dont work bruv

**Comment by pizzaboxer** [comment]
>  My answer given in the checkbox above is a lie.

Thank you for helpfully telling me that you didn't read the Wiki. https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder
