### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ky1e0** [pizzaboxer/bloxstrap#2432]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-07-19T21:26:36Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-07-19T21:26:36Z [App::OnStartup] Compiled Friday, 3 November 2023 at 5:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-07-19T21:26:36Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-07-19T21:26:36Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240719T212636Z.log
2024-07-19T21:26:36Z [Logger::Initialize] Finished initializing!
2024-07-19T21:26:36Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-07-19T21:26:36Z [JsonManager<Settings>::Load] Loaded successfully!
2024-07-19T21:26:36Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-19T21:26:36Z [JsonManager<State>::Load] Loaded successfully!
2024-07-19T21:26:36Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-19T21:26:36Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-07-19T21:26:36Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-07-19T21:26:36Z [App::OnStartup] Initializing bootstrapper
2024-07-19T21:26:36Z [App::OnStartup] Initializing bootstrapper dialog
2024-07-19T21:26:36Z [App::OnStartup] Creating singleton mutex
2024-07-19T21:26:36Z [Bootstrapper::Run] Running bootstrapper
2024-07-19T21:26:36Z [Bootstrapper::Run] Performing connectivity check...
2024-07-19T21:26:36Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-07-19T21:26:36Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-19T21:26:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-07-19T21:26:38Z [Bootstrapper::Run] Connectivity check finished
2024-07-19T21:26:38Z [RobloxDeployment::GetInfo] Getting deploy info for channel zqqiu-channel-adoption-1 (extraInformation=False)
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zqqiu-channel-adoption-1
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zqqiu-channel-adoption-1
2024-07-19T21:26:38Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-07-19T21:26:38Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-07-19T21:26:38Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-07-19T21:26:38Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/zqqiu-channel-adoption-1/version-09bed3002e5c41bd-rbxPkgManifest.txt
2024-07-19T21:26:38Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/zqqiu-channel-adoption-1/version-09bed3002e5c41bd-rbxPkgManifest.txt
2024-07-19T21:26:38Z [App::OnStartup] Bootstrapper task has finished
2024-07-19T21:26:38Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-07-19T21:26:38Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-07-19T21:26:38Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by ky1e0** [comment]
i can launch bloxstrap thru my alt, but not my main.

**Comment by nexpid** [comment]
> ```
> 2024-07-19T21:26:36Z [App::OnStartup] Starting Bloxstrap v2.5.4
> ```

update bloxstrap

**Comment by ky1e0** [comment]
> > ```
> > 2024-07-19T21:26:36Z [App::OnStartup] Starting Bloxstrap v2.5.4
> > ```
> 
> update bloxstrap

Resolve, ty
