### ISSUE TITLE
[BUG]  Can't find server locations, it keeps appearing lookout failed. 

### ISSUE THREAD

**Issue by SxpS1** [pizzaboxer/bloxstrap#2550]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Captura de tela 2024-08-01 191907](https://github.com/user-attachments/assets/eff6863f-22fc-4bf6-b027-6b640be5b747)

**Comment by pizzaboxer** [comment]
If this is still happening, launch Roblox again, get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` and send it here

**Comment by GitHubIdiotInTheWild** [comment]
> If this is still happening, launch Roblox again, get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` and send it here

i'm also experiencing it:


2024-08-07T15:05:56Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-07T15:05:56Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 9:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-07T15:05:56Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-08-07T15:05:57Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-07T15:05:57Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-08-07T15:05:57Z [JsonManager<Settings>::Load] Loaded successfully!
2024-08-07T15:05:57Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-08-07T15:05:57Z [JsonManager<State>::Load] Loaded successfully!
2024-08-07T15:05:57Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-07T15:05:57Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-08-07T15:05:57Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-08-07T15:05:57Z [JsonManager<State>::Save] Save request ignored
2024-08-07T15:05:57Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-07T15:05:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-07T15:05:57Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-07T15:05:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-07T15:05:58Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-07T15:05:58Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240807T150558Z.log
2024-08-07T15:05:58Z [Logger::Initialize] Finished initializing!
2024-08-07T15:05:58Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-08-07T15:05:58Z [App::OnStartup] Initializing bootstrapper
2024-08-07T15:05:58Z [App::OnStartup] Initializing bootstrapper dialog
2024-08-07T15:05:58Z [BootstrapperIconEx::GetIcon] Warning: custom icon is not set.
2024-08-07T15:05:58Z [BootstrapperIconEx::GetIcon] Warning: custom icon is not set.
2024-08-07T15:05:58Z [Bootstrapper::Run] Running bootstrapper
2024-08-07T15:05:58Z [Bootstrapper::Run] Performing connectivity check...
2024-08-07T15:05:58Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-08-07T15:05:58Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-07T15:05:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-07T15:05:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-07T15:05:59Z [Bootstrapper::Run] Connectivity check finished
2024-08-07T15:05:59Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-08-07T15:05:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-08-07T15:05:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-08-07T15:06:00Z [Bootstrapper::CheckForUpdates] No updates found
2024-08-07T15:06:00Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-07T15:06:00Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-07T15:06:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-01a570a3cd0a46f2-rbxPkgManifest.txt
2024-08-07T15:06:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-01a570a3cd0a46f2-rbxPkgManifest.txt
2024-08-07T15:06:00Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-07T15:06:00Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-08-07T15:06:00Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] ExtraContent\places\Mobile.rbxl has been copied to the version folder
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowCursor.png has been copied to the version folder
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowFarCursor.png has been copied to the version folder
2024-08-07T15:06:00Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-08-07T15:06:00Z [JsonManager<State>::Save] Save complete!
2024-08-07T15:06:00Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-08-07T15:06:00Z [Bootstrapper::CheckInstall] Checking install
2024-08-07T15:06:00Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-08-07T15:06:00Z [JsonManager<Settings>::Save] Save complete!
2024-08-07T15:06:00Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-08-07T15:06:00Z [JsonManager<State>::Save] Save complete!
2024-08-07T15:06:00Z [Bootstrapper::SetStatus] Starting {product}...
2024-08-07T15:06:00Z [Bootstrapper::StartRoblox] Started Roblox (PID 5480)
2024-08-07T15:06:00Z [Bootstrapper::StartRoblox] Using Discord Rich Presence
2024-08-07T15:06:03Z [NotifyIconWrapper::InitializeContextMenu] Initializing context menu
2024-08-07T15:06:03Z [ActivityWatcher::StartWatcher] Opening Roblox log file...
2024-08-07T15:06:03Z [ActivityWatcher::StartWatcher] Could not find recent enough log file, waiting... (newest is 0.636.1.6360627_20240807T150512Z_Player_179DC_last.log)
2024-08-07T15:06:03Z [Bootstrapper::StartRoblox] Waiting for Roblox to close
2024-08-07T15:06:04Z [ActivityWatcher::StartWatcher] Could not find recent enough log file, waiting... (newest is 0.636.1.6360627_20240807T150512Z_Player_179DC_last.log)
2024-08-07T15:06:05Z [ActivityWatcher::StartWatcher] Could not find recent enough log file, waiting... (newest is 0.636.1.6360627_20240807T150512Z_Player_179DC_last.log)
2024-08-07T15:06:06Z [ActivityWatcher::StartWatcher] Could not find recent enough log file, waiting... (newest is 0.636.1.6360627_20240807T150512Z_Player_179DC_last.log)
2024-08-07T15:06:07Z [ActivityWatcher::StartWatcher] Opened %UserProfile%\AppData\Local\Roblox\logs\0.636.1.6360627_20240807T150606Z_Player_01969_last.log
2024-08-07T15:06:08Z [ActivityWatcher::ExamineLogEntry] Read 50 log entries
2024-08-07T15:06:12Z [ActivityWatcher::ExamineLogEntry] Read 100 log entries
2024-08-07T15:06:12Z [ActivityWatcher::ExamineLogEntry] Joining Game (10449761463/cd97ab5c-0099-4a4d-80fd-ccbaabfb652c/10.18.8.26)
2024-08-07T15:06:12Z [ActivityWatcher::ExamineLogEntry] Server is UDMUX protected (10449761463/cd97ab5c-0099-4a4d-80fd-ccbaabfb652c/128.116.32.33)
2024-08-07T15:06:14Z [ActivityWatcher::ExamineLogEntry] Joined Game (10449761463/cd97ab5c-0099-4a4d-80fd-ccbaabfb652c/128.116.32.33)
2024-08-07T15:06:14Z [DiscordRichPresence::SetCurrentGame] Setting presence for Place ID 10449761463
2024-08-07T15:06:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://apis.roblox.com/universes/v1/places/10449761463/universe
2024-08-07T15:06:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.32.33/json
2024-08-07T15:06:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://apis.roblox.com/universes/v1/places/10449761463/universe
2024-08-07T15:06:15Z [DiscordRichPresence::SetCurrentGame] Got Universe ID as 3808081382
2024-08-07T15:06:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://games.roblox.com/v1/games?universeIds=3808081382
2024-08-07T15:06:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://games.roblox.com/v1/games?universeIds=3808081382
2024-08-07T15:06:16Z [DiscordRichPresence::SetCurrentGame] Got Universe details
2024-08-07T15:06:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://thumbnails.roblox.com/v1/games/icons?universeIds=3808081382&returnPolicy=PlaceHolder&size=512x512&format=Png&isCircular=false
2024-08-07T15:06:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://thumbnails.roblox.com/v1/games/icons?universeIds=3808081382&returnPolicy=PlaceHolder&size=512x512&format=Png&isCircular=false
2024-08-07T15:06:16Z [DiscordRichPresence::SetCurrentGame] Got Universe thumbnail as https://tr.rbxcdn.com/9b36fb6bcdcdac4b8d82739c6e39b244/512/512/Image/Png
2024-08-07T15:06:16Z [DiscordRichPresence::UpdatePresence] Updating presence
2024-08-07T15:06:16Z [ActivityWatcher::ExamineLogEntry] Read 150 log entries
2024-08-07T15:06:36Z [ActivityWatcher::GetServerLocation] Failed to get server location for 128.116.32.33
2024-08-07T15:06:39Z [ActivityWatcher::GetServerLocation] System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (ipinfo.io:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.Integrations.ActivityWatcher.GetServerLocation()
2024-08-07T15:06:39Z [NotifyIconWrapper::ShowAlert.017f0d42] Showing alert for 10 seconds (clickHandler=True)
2024-08-07T15:06:39Z [NotifyIconWrapper::ShowAlert.017f0d42] Connected to private server: Located at ? (lookup failed)
\nClick for more information
2024-08-07T15:06:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.32.33/json
2024-08-07T15:06:49Z [NotifyIconWrapper::ShowAlert.017f0d42] Duration over, erasing current click handler
2024-08-07T15:07:04Z [ActivityWatcher::GetServerLocation] Failed to get server location for 128.116.32.33
2024-08-07T15:07:04Z [ActivityWatcher::GetServerLocation] System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (ipinfo.io:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.Integrations.ActivityWatcher.GetServerLocation()

**Comment by pizzaboxer** [comment]
@GitHubIdiotInTheWild We use https://ipinfo.io for server locations, which you seem to be unable to contact for some reason. Check that please

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
