### ISSUE TITLE
sad ;-;

### ISSUE THREAD

**Issue by chuabip12** [pizzaboxer/bloxstrap#2556]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-08-03T05:37:28Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-03T05:37:28Z [App::OnStartup] Compiled Wednesday, 10 July 2024 at 1:03:19 AM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-03T05:37:28Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-08-03T05:37:28Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-03T05:37:28Z [LaunchSettings::Parse] No launch arguments to parse
2024-08-03T05:37:28Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-08-03T05:37:28Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-08-03T05:37:28Z [JsonManager<Settings>::Load] Loading from E:\Bloxstrap\Settings.json...
2024-08-03T05:37:28Z [JsonManager<Settings>::Load] Failed to load!
2024-08-03T05:37:28Z [JsonManager<Settings>::Load] Could not find a part of the path 'E:\Bloxstrap\Settings.json'.
2024-08-03T05:37:28Z [JsonManager<State>::Load] Loading from E:\Bloxstrap\State.json...
2024-08-03T05:37:28Z [JsonManager<State>::Load] Failed to load!
2024-08-03T05:37:28Z [JsonManager<State>::Load] Could not find a part of the path 'E:\Bloxstrap\State.json'.
2024-08-03T05:37:28Z [JsonManager<Dictionary`2>::Load] Loading from E:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-03T05:37:28Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-08-03T05:37:28Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'E:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
2024-08-03T05:37:28Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-08-03T05:37:28Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-08-03T05:37:28Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-03T05:37:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-03T05:37:28Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-03T05:37:29Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-03T05:37:29Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-03T05:37:29Z [Logger::Initialize] Initializing at E:\Bloxstrap\Logs\Bloxstrap_20240803T053729Z.log
2024-08-03T05:37:29Z [App::GlobalExceptionHandler] An exception occurred
2024-08-03T05:37:29Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'E:\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
You need to do a fresh reinstall. You'll first need to delete the registry key located at `HKEY_CURRENT_USER\Software\Bloxstrap` in the Windows Registry Editor before you can do that. Then after that you should be able to reinstall to a different location.
