### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by gexxlly** [pizzaboxer/bloxstrap#2565]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-08-04T10:28:36Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-04T10:28:36Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 11:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-04T10:28:36Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-08-04T10:28:36Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-04T10:28:36Z [LaunchSettings::Parse] No launch arguments to parse
2024-08-04T10:28:36Z [JsonManager<Settings>::Load] Loading from C:\Users\пися\AppData\Local\Bloxstrap\Settings.json...
2024-08-04T10:28:36Z [JsonManager<Settings>::Load] Loaded successfully!
2024-08-04T10:28:36Z [JsonManager<State>::Load] Loading from C:\Users\пися\AppData\Local\Bloxstrap\State.json...
2024-08-04T10:28:36Z [JsonManager<State>::Load] Loaded successfully!
2024-08-04T10:28:36Z [JsonManager<Dictionary`2>::Load] Loading from C:\Users\пися\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-04T10:28:36Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-08-04T10:28:36Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-08-04T10:28:36Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-04T10:28:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-04T10:28:36Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-04T10:28:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-04T10:28:37Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-04T10:28:37Z [Logger::Initialize] Initializing at C:\Users\пися\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240804T102837Z.log
2024-08-04T10:28:37Z [Logger::Initialize] Failed to initialize because Bloxstrap cannot write to C:\Users\пися\AppData\Local\Bloxstrap\Logs
2024-08-04T10:28:37Z [Frontend::ShowMessageBox] Файл журнала не будет написан для этого запуска, потому что Bloxstrap не может записать в папку в 'C:\Users\пися\AppData\Local\Bloxstrap\Logs'
2024-08-04T10:28:38Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-08-04T10:28:38Z [Frontend::ShowMessageBox] Запущенная версия Bloxstrap отличается от версии, которая установлена у вас сейчас.
Хотите ли вы обновить текущую версию?
2024-08-04T10:28:39Z [InstallChecker::CheckUpgrade] Waiting for write permissions to update version
2024-08-04T10:28:44Z [InstallChecker::CheckUpgrade] Failed to update! (Could not get write permissions after 5 seconds)
2024-08-04T10:28:44Z [App::OnStartup] Initializing bootstrapper
2024-08-04T10:28:44Z [App::OnStartup] Initializing bootstrapper dialog
2024-08-04T10:28:44Z [Bootstrapper::Run] Running bootstrapper
2024-08-04T10:28:44Z [Bootstrapper::Run] Performing connectivity check...
2024-08-04T10:28:44Z [Bootstrapper::SetStatus] Подключение к Roblox...
2024-08-04T10:28:44Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-04T10:28:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-04T10:28:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-04T10:28:44Z [Bootstrapper::Run] Connectivity check finished
2024-08-04T10:28:44Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-08-04T10:28:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-08-04T10:28:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-08-04T10:28:45Z [Bootstrapper::CheckForUpdates] No updates found
2024-08-04T10:28:45Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-04T10:28:45Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-04T10:28:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-01a570a3cd0a46f2-rbxPkgManifest.txt
2024-08-04T10:28:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-01a570a3cd0a46f2-rbxPkgManifest.txt
2024-08-04T10:28:45Z [JsonManager<Dictionary`2>::Save] Saving to C:\Users\пися\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-04T10:28:45Z [App::OnStartup] Bootstrapper task has finished
2024-08-04T10:28:45Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-08-04T10:28:45Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-08-04T10:28:45Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path 'C:\Users\пися\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\пися\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.FastFlagManager.Save()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
![image](https://github.com/user-attachments/assets/4d11748b-a486-4e90-a9cc-70fd35d49269)

im already clear appdata, but im still cant download bloxstrap

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

**Comment by pizzaboxer** [comment]
Looks like an antivirus issue. Check your antivirus to see if it's interfering.
