### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zezo011ma** [pizzaboxer/bloxstrap#2599]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-08-08T12:45:41Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-08-08T12:45:41Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 9:39:08 AM from DESKTOP-FGF6DO8\User
2024-08-08T12:45:41Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-08-08T12:45:41Z [InstallChecker::FirstTimeRun] Running first-time install
2024-08-08T12:45:41Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240808T124541Z.log
2024-08-08T12:45:41Z [Logger::Initialize] Finished initializing!
2024-08-08T12:45:41Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-08-08T12:45:41Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-08-08T12:45:41Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\ClientSettings\ClientAppSettings.json'.
2024-08-08T12:45:41Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-08-08T12:45:41Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-08-08T12:45:41Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-08-08T12:45:42Z [MainWindow::MainWindow] Initializing menu
2024-08-08T12:46:41Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-08-08T12:46:41Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-08-08T12:46:41Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-08-08T12:46:41Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-08-08T12:46:58Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=True)
2024-08-08T12:46:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-08T12:46:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-08T12:46:59Z [RobloxDeployment::GetInfo] Getting extra information...
2024-08-08T12:46:59Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-08-08T12:46:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-08T12:46:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-08T12:46:59Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-08-08T12:46:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T12:46:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T12:46:59Z [RobloxDeployment::GetInfo] https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt - Last-Modified: Tue, 06 Aug 2024 17:38:46 GMT
2024-08-08T12:47:20Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-08-08T12:47:20Z [App::OnStartup] Initializing bootstrapper
2024-08-08T12:47:20Z [App::OnStartup] Initializing bootstrapper dialog
2024-08-08T12:47:20Z [Bootstrapper::Run] Running bootstrapper
2024-08-08T12:47:20Z [Bootstrapper::Run] Performing connectivity check...
2024-08-08T12:47:20Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-08-08T12:47:20Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-08T12:47:20Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-08T12:47:20Z [Bootstrapper::Run] Connectivity check finished
2024-08-08T12:47:20Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-08T12:47:20Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxManifest.txt
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxManifest.txt
2024-08-08T12:47:20Z [Bootstrapper::SetStatus] Installing Roblox...
2024-08-08T12:47:20Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T12:47:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T12:48:30Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (83843123 bytes total)
2024-08-08T12:48:30Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-08-08T12:48:30Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-08-08T12:48:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-avatar.zip
2024-08-08T12:48:30Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd...
2024-08-08T12:48:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-avatar.zip
2024-08-08T12:48:31Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-08-08T12:48:31Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\avatar\...
2024-08-08T12:48:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-configs.zip
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-08-08T12:48:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-configs.zip
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-08-08T12:48:31Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (235542 bytes total)
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-08-08T12:48:31Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\configs\...
2024-08-08T12:48:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-fonts.zip
2024-08-08T12:48:31Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-08-08T12:48:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-fonts.zip
2024-08-08T12:48:37Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\fonts\...
2024-08-08T12:48:37Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-08-08T12:48:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-models.zip
2024-08-08T12:48:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-models.zip
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-08-08T12:48:37Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\models\...
2024-08-08T12:48:37Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-08-08T12:48:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sky.zip
2024-08-08T12:48:37Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-08-08T12:48:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sky.zip
2024-08-08T12:48:39Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-08-08T12:48:39Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\sky\...
2024-08-08T12:48:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sounds.zip
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-08-08T12:48:39Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sounds.zip
2024-08-08T12:48:39Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-08-08T12:48:39Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\sounds\...
2024-08-08T12:48:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-shaders.zip
2024-08-08T12:48:39Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-08-08T12:48:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-shaders.zip
2024-08-08T12:48:48Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8807941 bytes total)
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-08-08T12:48:48Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\shaders\...
2024-08-08T12:48:48Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-ssl.zip
2024-08-08T12:48:48Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-ssl.zip
2024-08-08T12:48:48Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (132363 bytes total)
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-08-08T12:48:48Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ssl\...
2024-08-08T12:48:48Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures2.zip
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-08-08T12:48:48Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures2.zip
2024-08-08T12:48:48Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-08-08T12:48:59Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (10099249 bytes total)
2024-08-08T12:48:59Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-08-08T12:48:59Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-08-08T12:48:59Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\textures\...
2024-08-08T12:48:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures3.zip
2024-08-08T12:48:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures3.zip
2024-08-08T12:49:01Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-08-08T12:49:02Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-08-08T12:49:02Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\textures\...
2024-08-08T12:49:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-terrain.zip
2024-08-08T12:49:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-terrain.zip
2024-08-08T12:49:02Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\terrain\...
2024-08-08T12:49:02Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-08-08T12:49:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-platform-fonts.zip
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-08-08T12:49:02Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-08-08T12:49:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-platform-fonts.zip
2024-08-08T12:49:13Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-08-08T12:49:13Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-08-08T12:49:13Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\fonts\...
2024-08-08T12:49:13Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-08-08T12:49:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-places.zip
2024-08-08T12:49:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-places.zip
2024-08-08T12:49:13Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-08-08T12:49:14Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1042079 bytes total)
2024-08-08T12:49:14Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-08-08T12:49:14Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-08-08T12:49:14Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\places\...
2024-08-08T12:49:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-luapackages.zip
2024-08-08T12:49:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-08-08T12:49:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-luapackages.zip
2024-08-08T12:49:22Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9450554 bytes total)
2024-08-08T12:49:22Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-08-08T12:49:22Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-08-08T12:49:22Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\LuaPackages\...
2024-08-08T12:49:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-translations.zip
2024-08-08T12:49:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-translations.zip
2024-08-08T12:49:22Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-08-08T12:49:23Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (422356 bytes total)
2024-08-08T12:49:23Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-08-08T12:49:23Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-08-08T12:49:23Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\translations\...
2024-08-08T12:49:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-models.zip
2024-08-08T12:49:23Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-08-08T12:49:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-models.zip
2024-08-08T12:49:31Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (9485181 bytes total)
2024-08-08T12:49:31Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-08-08T12:49:31Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-08-08T12:49:31Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\models\...
2024-08-08T12:49:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-textures.zip
2024-08-08T12:49:31Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-08-08T12:49:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-textures.zip
2024-08-08T12:49:42Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (14206859 bytes total)
2024-08-08T12:49:42Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-08-08T12:49:42Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\textures\...
2024-08-08T12:49:42Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-08-08T12:49:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2.zip
2024-08-08T12:49:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2.zip
2024-08-08T12:49:42Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-08-08T12:49:42Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-08-08T12:49:42Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-08-08T12:49:42Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd...
2024-08-08T12:49:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2RuntimeInstaller.zip
2024-08-08T12:49:42Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-08-08T12:49:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2RuntimeInstaller.zip
2024-08-08T12:49:43Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-08-08T12:49:44Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-08-08T12:49:45Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-08-08T12:49:45Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-08-08T12:49:45Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-08T12:49:45Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-08-08T12:49:45Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-08-08T12:49:45Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-08-08T12:49:45Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-08-08T12:49:45Z [Bootstrapper::CheckModPreset.Sounds.OldDeath.ogg] Writing 'content\sounds\ouch.ogg' as preset is enabled, and mod file does not exist or does not match preset
2024-08-08T12:49:45Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-08-08T12:49:45Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-08-08T12:49:45Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-08-08T12:49:45Z [JsonManager<State>::Save] Save complete!
2024-08-08T12:49:45Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-08-08T12:49:45Z [Bootstrapper::Register] Registered application
2024-08-08T12:49:45Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-08-08T12:49:45Z [Bootstrapper::RegisterProgramSize] Registered as 432828 KB
2024-08-08T12:49:45Z [Bootstrapper::CheckInstall] Checking install
2024-08-08T12:49:45Z [App::OnStartup] Bootstrapper task has finished
2024-08-08T12:49:45Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-08-08T12:49:45Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-08-08T12:49:45Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by zezo011ma** [comment]
that sucks
