### ISSUE TITLE
[BUG] An Exception error

### ISSUE THREAD

**Issue by FlukeMaster05** [pizzaboxer/bloxstrap#2605]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

not exactly sure what to do here

2024-08-08T21:25:09Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-08-08T21:25:09Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 6:39:08 PM from DESKTOP-FGF6DO8\User
2024-08-08T21:25:09Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-08-08T21:25:09Z [InstallChecker::FirstTimeRun] Running first-time install
2024-08-08T21:25:09Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20240808T212509Z.log
2024-08-08T21:25:09Z [Logger::Initialize] Finished initializing!
2024-08-08T21:25:09Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-08-08T21:25:09Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-08-08T21:25:09Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Wave\ClientSettings\ClientAppSettings.json'.
2024-08-08T21:25:09Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-08-08T21:25:09Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-08-08T21:25:09Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-08-08T21:25:09Z [MainWindow::MainWindow] Initializing menu
2024-08-08T21:27:35Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-08-08T21:27:35Z [App::OnStartup] Initializing bootstrapper
2024-08-08T21:27:35Z [App::OnStartup] Initializing bootstrapper dialog
2024-08-08T21:27:35Z [Bootstrapper::Run] Running bootstrapper
2024-08-08T21:27:35Z [Bootstrapper::Run] Performing connectivity check...
2024-08-08T21:27:35Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-08-08T21:27:35Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-08T21:27:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-08T21:27:36Z [Bootstrapper::Run] Connectivity check finished
2024-08-08T21:27:36Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-08T21:27:36Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-08T21:27:36Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-08T21:27:36Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxPkgManifest.txt
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxManifest.txt
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-rbxManifest.txt
2024-08-08T21:27:36Z [Bootstrapper::SetStatus] Installing Roblox...
2024-08-08T21:27:36Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T21:27:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T21:27:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] An exception occurred after downloading 8276995 bytes. (1/5)
2024-08-08T21:27:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder.SetResult()
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteAsyncSlowPath(Task semaphoreLockTask, ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-08-08T21:27:37Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Retrying download over HTTP...
2024-08-08T21:27:37Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T21:27:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup.rbxcdn.com/version-6fdcfe060c6440cd-RobloxApp.zip
2024-08-08T21:28:04Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (83843123 bytes total)
2024-08-08T21:28:04Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-08-08T21:28:04Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-08-08T21:28:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-avatar.zip
2024-08-08T21:28:04Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd...
2024-08-08T21:28:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-avatar.zip
2024-08-08T21:28:04Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-08-08T21:28:04Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-08-08T21:28:04Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-08-08T21:28:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-configs.zip
2024-08-08T21:28:04Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\avatar\...
2024-08-08T21:28:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-configs.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (235542 bytes total)
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-fonts.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\configs\...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-fonts.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-models.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\fonts\...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-models.zip
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sky.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\models\...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sky.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sounds.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\sky\...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-sounds.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-08-08T21:28:05Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-shaders.zip
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\sounds\...
2024-08-08T21:28:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-08-08T21:28:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-shaders.zip
2024-08-08T21:28:06Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8807941 bytes total)
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-08-08T21:28:06Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-08-08T21:28:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-ssl.zip
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\shaders\...
2024-08-08T21:28:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-ssl.zip
2024-08-08T21:28:06Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (132363 bytes total)
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-08-08T21:28:06Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-08-08T21:28:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures2.zip
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ssl\...
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-08-08T21:28:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures2.zip
2024-08-08T21:28:06Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (10099249 bytes total)
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures3.zip
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\content\textures\...
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-textures3.zip
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-terrain.zip
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\textures\...
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-terrain.zip
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-08-08T21:28:07Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-platform-fonts.zip
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\terrain\...
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-08-08T21:28:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-content-platform-fonts.zip
2024-08-08T21:28:07Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-08-08T21:28:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-08-08T21:28:09Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-08-08T21:28:09Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-08-08T21:28:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-places.zip
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\PlatformContent\pc\fonts\...
2024-08-08T21:28:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-places.zip
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-08-08T21:28:09Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1042079 bytes total)
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-08-08T21:28:09Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-08-08T21:28:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-luapackages.zip
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\places\...
2024-08-08T21:28:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-luapackages.zip
2024-08-08T21:28:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9450554 bytes total)
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-translations.zip
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\LuaPackages\...
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-translations.zip
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (422356 bytes total)
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-models.zip
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\translations\...
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-models.zip
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (9485181 bytes total)
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-08-08T21:28:10Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-textures.zip
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\models\...
2024-08-08T21:28:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-extracontent-textures.zip
2024-08-08T21:28:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-08-08T21:28:12Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (14206859 bytes total)
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-08-08T21:28:12Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-08-08T21:28:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2.zip
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd\ExtraContent\textures\...
2024-08-08T21:28:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2.zip
2024-08-08T21:28:12Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-08-08T21:28:12Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-08-08T21:28:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2RuntimeInstaller.zip
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-6fdcfe060c6440cd...
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-08-08T21:28:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6fdcfe060c6440cd-WebView2RuntimeInstaller.zip
2024-08-08T21:28:12Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-08-08T21:28:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-08-08T21:28:13Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-08-08T21:28:13Z [Bootstrapper::InstallLatestVersion] Writing AppSettings.xml...
2024-08-08T21:28:13Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-08T21:28:13Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-08-08T21:28:13Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-08-08T21:28:13Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-08-08T21:28:13Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-08-08T21:28:13Z [Bootstrapper::CheckModPreset.Sounds.OldDeath.ogg] Writing 'content\sounds\ouch.ogg' as preset is enabled, and mod file does not exist or does not match preset
2024-08-08T21:28:13Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-08-08T21:28:13Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-08-08T21:28:13Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-08-08T21:28:13Z [JsonManager<State>::Save] Save complete!
2024-08-08T21:28:13Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-08-08T21:28:13Z [Bootstrapper::Register] Registered application
2024-08-08T21:28:13Z [Bootstrapper::RegisterProgramSize] Registering approximate program size...
2024-08-08T21:28:13Z [Bootstrapper::RegisterProgramSize] Registered as 432828 KB
2024-08-08T21:28:13Z [Bootstrapper::CheckInstall] Checking install
2024-08-08T21:28:13Z [App::OnStartup] Bootstrapper task has finished
2024-08-08T21:28:13Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-08-08T21:28:13Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-08-08T21:28:13Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Bloxstrap.Bootstrapper.CheckInstall()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
Read the Wiki
