### ISSUE TITLE
HELP WITH BLOXSTRAP

### ISSUE THREAD

**Issue by Tapok52** [pizzaboxer/bloxstrap#2613]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-08-09T14:36:36Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-09T14:36:36Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 11:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-09T14:36:36Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-08-09T14:36:36Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-09T14:36:36Z [LaunchSettings::Parse] No launch arguments to parse
2024-08-09T14:36:36Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-08-09T14:36:36Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-08-09T14:36:36Z [JsonManager<Settings>::Load] Loading from C:\Users\ПК\AppData\Local\Bloxstrap\Settings.json...
2024-08-09T14:36:36Z [JsonManager<Settings>::Load] Failed to load!
2024-08-09T14:36:36Z [JsonManager<Settings>::Load] Could not find a part of the path 'C:\Users\ПК\AppData\Local\Bloxstrap\Settings.json'.
2024-08-09T14:36:36Z [JsonManager<State>::Load] Loading from C:\Users\ПК\AppData\Local\Bloxstrap\State.json...
2024-08-09T14:36:36Z [JsonManager<State>::Load] Failed to load!
2024-08-09T14:36:36Z [JsonManager<State>::Load] Could not find a part of the path 'C:\Users\ПК\AppData\Local\Bloxstrap\State.json'.
2024-08-09T14:36:36Z [JsonManager<Dictionary`2>::Load] Loading from C:\Users\ПК\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-09T14:36:36Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-08-09T14:36:36Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Users\ПК\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
2024-08-09T14:36:36Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-08-09T14:36:36Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-08-09T14:36:36Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-09T14:36:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-09T14:36:36Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-09T14:36:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-09T14:36:37Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-09T14:36:37Z [Logger::Initialize] Initializing at C:\Users\ПК\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240809T143637Z.log
2024-08-09T14:36:37Z [App::GlobalExceptionHandler] An exception occurred
2024-08-09T14:36:37Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\ПК\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie

> [!WARNING]
> Please read the preliminary instructions before reading.

Please check if your Bloxstrap folder is still there; have you moved or deleted the Bloxstrap folder.? (`%localappdata%\Bloxstrap` )

**Comment by pizzaboxer** [comment]
Seems like an antivirus issue. Check your antivirus to make sure it won't be interfering with Bloxstrap.

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
