### ISSUE TITLE
issue on parameter(An exception occured while running bloxstrp)

### ISSUE THREAD

**Issue by NIGERsourus** [pizzaboxer/bloxstrap#2618]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2024-08-09T14:08:18Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-09T14:08:18Z [App::OnStartup] Compiled Wednesday, 10 July 2024 at 2:03:19 AM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-09T14:08:18Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-08-09T14:08:18Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-09T14:08:18Z [LaunchSettings::Parse] No launch arguments to parse
2024-08-09T14:08:18Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-08-09T14:08:18Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-08-09T14:08:18Z [JsonManager<Settings>::Load] Loading from F:\GAem\Settings.json...
2024-08-09T14:08:18Z [JsonManager<Settings>::Load] Failed to load!
2024-08-09T14:08:18Z [JsonManager<Settings>::Load] The parameter is incorrect. : 'F:\GAem\Settings.json'
2024-08-09T14:08:18Z [JsonManager<State>::Load] Loading from F:\GAem\State.json...
2024-08-09T14:08:18Z [JsonManager<State>::Load] Failed to load!
2024-08-09T14:08:18Z [JsonManager<State>::Load] The parameter is incorrect. : 'F:\GAem\State.json'
2024-08-09T14:08:18Z [JsonManager<Dictionary`2>::Load] Loading from F:\GAem\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-09T14:08:18Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-08-09T14:08:18Z [JsonManager<Dictionary`2>::Load] The parameter is incorrect. : 'F:\GAem\Modifications\ClientSettings\ClientAppSettings.json'
2024-08-09T14:08:18Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-08-09T14:08:18Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-08-09T14:08:18Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-09T14:08:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-09T14:08:18Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-09T14:08:19Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-09T14:08:19Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-09T14:08:19Z [Logger::Initialize] Initializing at F:\GAem\Logs\Bloxstrap_20240809T140819Z.log
2024-08-09T14:08:19Z [App::GlobalExceptionHandler] An exception occurred
2024-08-09T14:08:19Z [App::FinalizeExceptionHandling] System.IO.IOException: The parameter is incorrect. : 'F:\GAem\Logs'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ShadowCodeX-debug** [comment]
Uhh did you maybe move your Bloxstrap folder manually?

**Comment by pizzaboxer** [comment]
What's the F:\ drive for?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
