### ISSUE TITLE
i don't think that this is in the wiki

### ISSUE THREAD

**Issue by Rathshark** [pizzaboxer/bloxstrap#2772]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

this was not happening yesterday

2024-08-29T08:52:20Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-08-29T08:52:20Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 8:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-08-29T08:52:20Z [App::OnStartup] Loaded from C:\stuff\programs\bloxtrap\Bloxstrap.exe
2024-08-29T08:52:20Z [LaunchSettings::Parse] Parsing launch arguments
2024-08-29T08:52:20Z [JsonManager<Settings>::Load] Loading from C:\stuff\programs\bloxtrap\Settings.json...
2024-08-29T08:52:20Z [JsonManager<Settings>::Load] Loaded successfully!
2024-08-29T08:52:20Z [JsonManager<State>::Load] Loading from C:\stuff\programs\bloxtrap\State.json...
2024-08-29T08:52:20Z [JsonManager<State>::Load] Loaded successfully!
2024-08-29T08:52:20Z [JsonManager<Dictionary`2>::Load] Loading from C:\stuff\programs\bloxtrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-29T08:52:20Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-08-29T08:52:20Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-08-29T08:52:20Z [JsonManager<State>::Save] Save request ignored
2024-08-29T08:52:20Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-08-29T08:52:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-08-29T08:52:20Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-08-29T08:52:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-08-29T08:52:20Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-08-29T08:52:20Z [Logger::Initialize] Initializing at C:\stuff\programs\bloxtrap\Logs\Bloxstrap_20240829T085220Z.log
2024-08-29T08:52:20Z [Logger::Initialize] Failed to initialize because Bloxstrap cannot write to C:\stuff\programs\bloxtrap\Logs
2024-08-29T08:52:20Z [Frontend::ShowMessageBox] No log file will be written for this launch because Bloxstrap is unable to write to the folder at 'C:\stuff\programs\bloxtrap\Logs'
2024-08-29T08:52:33Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-08-29T08:52:33Z [App::OnStartup] Initializing bootstrapper
2024-08-29T08:52:33Z [App::OnStartup] Initializing bootstrapper dialog
2024-08-29T08:52:33Z [Bootstrapper::Run] Running bootstrapper
2024-08-29T08:52:33Z [Bootstrapper::Run] Performing connectivity check...
2024-08-29T08:52:33Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-08-29T08:52:33Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-29T08:52:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-29T08:52:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-08-29T08:52:34Z [Bootstrapper::Run] Connectivity check finished
2024-08-29T08:52:34Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-08-29T08:52:34Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-08-29T08:52:34Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-08-29T08:52:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-ad321ed0d27f48b2-rbxPkgManifest.txt
2024-08-29T08:52:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-ad321ed0d27f48b2-rbxPkgManifest.txt
2024-08-29T08:52:34Z [JsonManager<Dictionary`2>::Save] Saving to C:\stuff\programs\bloxtrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-08-29T08:52:34Z [App::OnStartup] Bootstrapper task has finished
2024-08-29T08:52:34Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-08-29T08:52:34Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-08-29T08:52:34Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Access to the path 'C:\stuff\programs\bloxtrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\stuff\programs\bloxtrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.FastFlagManager.Save()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
![afbeelding_2024-08-29_105652673](https://github.com/user-attachments/assets/ed11e550-4d51-48fa-a4c5-21f2351ef64a)
![afbeelding_2024-08-29_105715762](https://github.com/user-attachments/assets/356ffc22-fe2a-4d36-b469-3b08b3a4b1cb)

**Comment by Rathshark** [comment]
i didn't think i could do that

**Comment by Rathshark** [comment]
im gonna install bloxtrap from the right sourse first

**Comment by Rathshark** [comment]
that did it
