### ISSUE TITLE
[BUG] Bloxstrap not launching.

### ISSUE THREAD

**Issue by Kazmaajan** [pizzaboxer/bloxstrap#2806]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I click to play roblox, it says I'm connecting to roblox, then roblox doesn't open and the mini bloxstrap tray is gone. im using the latest .NET 6 (6.0.33) im using Windows 11. I readed the previous fixed bug reports and mine didnt fixed. Also without bloxstrap its still same (doesn't launching).

### Bloxstrap Log

2024-09-03T11:03:20Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-09-03T11:03:20Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 9:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-09-03T11:03:20Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-09-03T11:03:20Z [LaunchSettings::Parse] Parsing launch arguments
2024-09-03T11:03:20Z [LaunchSettings::Parse] No launch arguments to parse
2024-09-03T11:03:20Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-09-03T11:03:21Z [JsonManager<Settings>::Load] Loaded successfully!
2024-09-03T11:03:21Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-09-03T11:03:21Z [JsonManager<State>::Load] Loaded successfully!
2024-09-03T11:03:21Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-09-03T11:03:21Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-09-03T11:03:21Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-09-03T11:03:21Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-09-03T11:03:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-09-03T11:03:21Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-09-03T11:03:23Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] Connecting...
2024-09-03T11:03:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version
2024-09-03T11:03:23Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] Connecting...
2024-09-03T11:03:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version
2024-09-03T11:03:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/version
2024-09-03T11:03:23Z [RobloxDeployment::InitializeConnectivity] Got https://roblox-setup.cachefly.net as the optimal base URL
2024-09-03T11:03:23Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240903T110323Z.log
2024-09-03T11:03:23Z [Logger::Initialize] Finished initializing!
2024-09-03T11:03:23Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-09-03T11:03:24Z [App::OnStartup] Initializing bootstrapper
2024-09-03T11:03:24Z [App::OnStartup] Initializing bootstrapper dialog
2024-09-03T11:03:24Z [Bootstrapper::Run] Running bootstrapper
2024-09-03T11:03:24Z [Bootstrapper::Run] Performing connectivity check...
2024-09-03T11:03:24Z [Bootstrapper::SetStatus] Roblox'a bağlanılıyor...
2024-09-03T11:03:24Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-09-03T11:03:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-09-03T11:03:51Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-09-03T11:03:53Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-09-03T11:03:54Z [RobloxDeployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-09-03T11:03:54Z [RobloxDeployment::GetInfo] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.GetInfo(String channel, Boolean extraInformation, String binaryType)
2024-09-03T11:03:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-09-03T11:03:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-09-03T11:03:55Z [Bootstrapper::Run] Connectivity check finished
2024-09-03T11:03:55Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-09-03T11:03:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-09-03T11:03:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-09-03T11:03:55Z [Bootstrapper::CheckForUpdates] No updates found
2024-09-03T11:03:55Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-09-03T11:03:55Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-09-03T11:03:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version-ad321ed0d27f48b2-rbxPkgManifest.txt
2024-09-03T11:03:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/version-ad321ed0d27f48b2-rbxPkgManifest.txt
2024-09-03T11:03:55Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-09-03T11:03:55Z [JsonManager<Dictionary`2>::Save] Save complete!
2024-09-03T11:03:55Z [Bootstrapper::SetStatus] Roblox modifikasyonları uygulanıyor...
2024-09-03T11:03:55Z [Bootstrapper::ApplyModifications] Checking executable flags...
2024-09-03T11:03:55Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-09-03T11:03:55Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-09-03T11:03:55Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg already exists in the version folder, and is a match
2024-09-03T11:03:55Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-09-03T11:03:55Z [JsonManager<State>::Save] Save complete!
2024-09-03T11:03:55Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-09-03T11:03:55Z [Bootstrapper::CheckInstall] Checking install
2024-09-03T11:03:55Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-09-03T11:03:55Z [JsonManager<Settings>::Save] Save complete!
2024-09-03T11:03:55Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-09-03T11:03:55Z [JsonManager<State>::Save] Save complete!
2024-09-03T11:03:55Z [Bootstrapper::SetStatus] {product} başlatılıyor...
2024-09-03T11:03:56Z [Bootstrapper::StartRoblox] Started Roblox (PID 9748)
2024-09-03T11:03:59Z [App::OnStartup] Bootstrapper task has finished
2024-09-03T11:03:59Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-09-03T11:03:59Z [App::OnStartup] Waiting for bootstrapper task to finish
2024-09-03T11:03:59Z [App::StartupFinished] Successfully reached end of main thread. Terminating...
2024-09-03T11:03:59Z [App::Terminate] Terminating with exit code 0 (ERROR_SUCCESS)

**Comment by Kazmaajan** [comment]
![image](https://github.com/user-attachments/assets/6200ace5-b701-48b8-bc67-c051fc5c28b5)

**Comment by Kazmaajan** [comment]
The problem that causes the crash was the fps unlocker. If i set the value to 0 (default) it fixes the problem.
