### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PrinsKorven** [pizzaboxer/bloxstrap#2909]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### Bloxstrap Log

2024-09-19T16:42:21Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-09-19T16:42:21Z [App::OnStartup] Compiled Friday, 3 November 2023 at 10:46:02 PM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-09-19T16:42:21Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-09-19T16:42:21Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20240919T164221Z.log
2024-09-19T16:42:21Z [Logger::Initialize] Finished initializing!
2024-09-19T16:42:21Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-09-19T16:42:21Z [JsonManager<Settings>::Load] Loaded successfully!
2024-09-19T16:42:21Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-09-19T16:42:21Z [JsonManager<State>::Load] Loaded successfully!
2024-09-19T16:42:21Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-09-19T16:42:21Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-09-19T16:42:21Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-09-19T16:42:21Z [JsonManager<State>::Save] Save request ignored
2024-09-19T16:42:21Z [App::OnStartup] Initializing bootstrapper
2024-09-19T16:42:21Z [App::OnStartup] Initializing bootstrapper dialog
2024-09-19T16:42:21Z [App::OnStartup] Creating singleton mutex
2024-09-19T16:42:21Z [Bootstrapper::Run] Running bootstrapper
2024-09-19T16:42:21Z [Bootstrapper::Run] Performing connectivity check...
2024-09-19T16:42:21Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-09-19T16:42:21Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-09-19T16:42:21Z [Bootstrapper::Run] Connectivity check finished
2024-09-19T16:42:21Z [RobloxDeployment::GetInfo] Getting deploy info for channel zhighenrollmentmetricstest (extraInformation=False)
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zhighenrollmentmetricstest
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zhighenrollmentmetricstest
2024-09-19T16:42:21Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-09-19T16:42:21Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-09-19T16:42:21Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-09-19T16:42:21Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-09-19T16:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/zhighenrollmentmetricstest/version-43ad1853ad91427d-rbxPkgManifest.txt
2024-09-19T16:42:22Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/zhighenrollmentmetricstest/version-43ad1853ad91427d-rbxPkgManifest.txt
2024-09-19T16:42:22Z [App::OnStartup] Bootstrapper task has finished
2024-09-19T16:42:22Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-09-19T16:42:22Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-09-19T16:42:22Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by NabHeyka22** [comment]
how come you put a check on i've read the wiki and the bug isn't addressed when the problem is on the wiki
anyways update
use roblox account manager if you want multi instance
if you don't want to update, we won't help you in any way

**Comment by bluepilledgreat** [comment]
We don't support older versions of Bloxstrap.
