### ISSUE TITLE
Roblox doenst launch

### ISSUE THREAD

**Issue by SLAYGE** [pizzaboxer/bloxstrap#3038]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

idk how to fix this

### Bloxstrap Log

024-10-03T17:51:51Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-10-03T17:51:51Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 9:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-10-03T17:51:51Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-03T17:51:51Z [LaunchSettings::Parse] Parsing launch arguments
2024-10-03T17:51:51Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-03T17:51:51Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-03T17:51:51Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-03T17:51:51Z [JsonManager<State>::Load] Loaded successfully!
2024-10-03T17:51:51Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-03T17:51:51Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-10-03T17:51:51Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-10-03T17:51:51Z [ProtocolHandler::ChangeChannel] Changed Roblox channel from LIVE to zaflag
2024-10-03T17:51:51Z [JsonManager<State>::Save] Save request ignored
2024-10-03T17:51:51Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-10-03T17:51:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-03T17:51:51Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-10-03T17:51:51Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-03T17:51:51Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-03T17:51:51Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241003T175151Z.log
2024-10-03T17:51:51Z [Logger::Initialize] Finished initializing!
2024-10-03T17:51:51Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-03T17:51:51Z [App::OnStartup] Initializing bootstrapper
2024-10-03T17:51:51Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-03T17:51:51Z [Bootstrapper::Run] Running bootstrapper
2024-10-03T17:51:51Z [Bootstrapper::Run] Performing connectivity check...
2024-10-03T17:51:51Z [Bootstrapper::SetStatus] Подключение к Roblox...
2024-10-03T17:51:51Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-03T17:51:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-03T17:51:52Z [Bootstrapper::Run] Connectivity check finished
2024-10-03T17:51:52Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-03T17:51:52Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-03T17:51:52Z [RobloxDeployment::GetInfo] Getting deploy info for channel zaflag (extraInformation=False)
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zaflag
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zaflag
2024-10-03T17:51:52Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-03T17:51:52Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-03T17:51:52Z [RobloxFastFlags::Fetch.PCClientBootstrapper.zaflag] Fetching fast flags
2024-10-03T17:51:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaflag
2024-10-03T17:51:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaflag
2024-10-03T17:51:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-72ed2b2ad9e5447f-rbxPkgManifest.txt
2024-10-03T17:51:53Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/common/version-72ed2b2ad9e5447f-rbxPkgManifest.txt
2024-10-03T17:51:53Z [App::OnStartup] Bootstrapper task has finished
2024-10-03T17:51:53Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-10-03T17:51:53Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-10-03T17:51:53Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by NabHeyka22** [comment]
This is possibly an issue Roblox made by doing something wrong.
Please wait until Roblox themselves fix this issue.
