### ISSUE TITLE
Encountering 403 (Forbidden) Error even using latest version of Bloxstrap

### ISSUE THREAD

**Issue by Skibidi1927** [pizzaboxer/bloxstrap#3043]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

This issue should be fixed with downloading latest version but it doesn't so i guess it might be a bugs of the programs itself and only me encountered this?

![image](https://github.com/user-attachments/assets/9e4f13cd-8884-43b5-b1a9-18c2645b7646)

### Bloxstrap Log

2024-10-03T17:55:02Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-10-03T17:55:02Z [App::OnStartup] Compiled Wednesday, 10 July 2024 at 1:03:19 AM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-10-03T17:55:02Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-10-03T17:55:02Z [LaunchSettings::Parse] Parsing launch arguments
2024-10-03T17:55:02Z [LaunchSettings::Parse] No launch arguments to parse
2024-10-03T17:55:02Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-03T17:55:02Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-03T17:55:02Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-03T17:55:02Z [JsonManager<State>::Load] Loaded successfully!
2024-10-03T17:55:02Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-03T17:55:02Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-10-03T17:55:02Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-10-03T17:55:02Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-10-03T17:55:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-03T17:55:02Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-10-03T17:55:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-03T17:55:03Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-03T17:55:03Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_25671003T175503Z.log
2024-10-03T17:55:03Z [Logger::Initialize] Finished initializing!
2024-10-03T17:55:03Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-03T17:55:04Z [App::OnStartup] Initializing bootstrapper
2024-10-03T17:55:04Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-03T17:55:04Z [Bootstrapper::Run] Running bootstrapper
2024-10-03T17:55:04Z [Bootstrapper::Run] Performing connectivity check...
2024-10-03T17:55:04Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-03T17:55:04Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-03T17:55:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-03T17:55:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-03T17:55:04Z [Bootstrapper::Run] Connectivity check finished
2024-10-03T17:55:04Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-03T17:55:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-03T17:55:05Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-03T17:55:05Z [RobloxDeployment::GetInfo] Getting deploy info for channel zassetcacheinitprod (extraInformation=False)
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zassetcacheinitprod
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zassetcacheinitprod
2024-10-03T17:55:05Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-03T17:55:05Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-03T17:55:05Z [RobloxFastFlags::Fetch.PCClientBootstrapper.zassetcacheinitprod] Fetching fast flags
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zassetcacheinitprod
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zassetcacheinitprod
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-72ed2b2ad9e5447f-rbxPkgManifest.txt
2024-10-03T17:55:05Z [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/common/version-72ed2b2ad9e5447f-rbxPkgManifest.txt
2024-10-03T17:55:05Z [App::OnStartup] Bootstrapper task has finished
2024-10-03T17:55:05Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-10-03T17:55:05Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-10-03T17:55:05Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
2024-10-03T18:04:12Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
2024-10-03T18:04:12Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-03T18:04:12Z [JsonManager<Settings>::Save] Save complete!
2024-10-03T18:04:12Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-03T18:04:12Z [JsonManager<State>::Save] Save complete!

**Comment by NabHeyka22** [comment]
Read. Other. Posts. I'm begging you. Please. Just do it. Save us time. PLEASE.
