### ISSUE TITLE
[BUG] System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by ZombieStebo** [pizzaboxer/bloxstrap#3741]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

When I tried to play a game buy using the website it opened the error message

### Bloxstrap Log

```text
2024-11-10T23:26:06Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-10T23:26:06Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-10T23:26:06Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-10T23:26:06Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-10T23:26:06Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-10T23:26:06Z [LaunchSettings] Identifier 'player' is active with data
2024-11-10T23:26:06Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241110T232606Z.log
2024-11-10T23:26:06Z [Logger::Initialize] Finished initializing!
2024-11-10T23:26:06Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241103T220616Z.log'
2024-11-10T23:26:06Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-10T23:26:06Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-10T23:26:06Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-10T23:26:06Z [JsonManager<State>::Load] Loaded successfully!
2024-11-10T23:26:06Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-10T23:26:06Z [FastFlagManager::Load] Loaded successfully!
2024-11-10T23:26:06Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-10T23:26:06Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-10T23:26:06Z [Bootstrapper::Run] Running bootstrapper
2024-11-10T23:26:06Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-10T23:26:06Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-10T23:26:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-10T23:26:07Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-10T23:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-10T23:26:07Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-10T23:26:07Z [Bootstrapper::Run] Connectivity check finished
2024-11-10T23:26:07Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-11-10T23:26:07Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-10T23:26:07Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-10T23:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-10T23:26:07Z [App::GlobalExceptionHandler] An exception occurred
2024-11-10T23:26:07Z [App::FinalizeExceptionHandling] (0x80004001) System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-11-10T23:26:07Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by theletron** [comment]
Do you use RemoteApp?

**Comment by sinteran** [comment]
me too and how to fix ??

**Comment by theletron** [comment]
@bluepilledgreat  

This issue happens to people who use RemoteApp. And sometimes for those who don’t.

https://github.com/dotnet/wpf/issues/2377
https://github.com/Tyrrrz/DiscordChatExporter/issues/297

I believe this issue is with the version of .NET being used.
A fix for this issue has already been made. But not for this .NET version.

https://github.com/dotnet/wpf/commit/c308dfcad75d7b491ea88d39118fb8aee70d6b87

6.0 reached it's EoS last year.
The only way to fix this is to update .NET, I think. I don't know if this problem can be fixed by updating WPF UI.

https://github.com/dotnet/wpf/issues/8072

Duplicates:
#3963

**Comment by Koffee-Blox** [comment]
This problem is not being fixed even by updating .NET.

**Comment by pr0xim1ty** [comment]
> This problem is not being fixed even by updating .NET.

Not your .NET version, the project’s .NET version.

**Comment by Koffee-Blox** [comment]
I am actuallly talking about the the same problem with bloxstrap 2.9.0. And may you please clarify yourself.

**Comment by Koffee-Blox** [comment]
will test.
