### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by Herobrine8761** [pizzaboxer/bloxstrap#407]
![Robloxdied](https://github.com/pizzaboxer/bloxstrap/assets/77039018/52c0a155-5b7b-4744-9b1b-bf25c0ef5ba3)

Yeah... I am not a decent code guy, so I could use some help.

(System info: Windows 11 Home Edition (No TPM or Secure Boot), 16GB RAM, 480GB SSD (117GB free), "Intel(R) Core(TM) i7-8700 CPU", and 64-bit operating system)

**Comment by pizzaboxer** [comment]
Seems like an SSL error. The latest version doesn't show enough details when an error occurs, so try using a build of the next upcoming version, and report the error that comes from there, along with a copy of the log file. Download https://github.com/pizzaboxer/bloxstrap/suites/14457101081/artifacts/816346381 and just run Bloxstrap.exe.

**Comment by Herobrine8761** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/77039018/1508c9ff-389e-4f3b-a73c-40786196d995)

**--LOG START--**
2023-08-05T10:48:19Z [App::OnStartup] Starting Bloxstrap v2.4.0
2023-08-05T10:48:19Z [App::OnStartup] Compiled Friday, 21 July 2023 at 4:37:06 AM from commit 62b4897bccf24b113287c7bbeae2697705a08ab7 (branch/version-2.4.0)
2023-08-05T10:48:19Z [App::OnStartup] Running first-time install
2023-08-05T10:48:19Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20230805T104819Z.log
2023-08-05T10:48:19Z [Logger::Initialize] Finished initializing!
2023-08-05T10:48:19Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2023-08-05T10:48:19Z [JsonManager<Dictionary`2>::Load] Failed to load! (Could not find a part of the path '%UserProfile%\AppData\Local\Temp\360zip$Temp\360$0\ClientSettings\ClientAppSettings.json'.)
2023-08-05T10:48:19Z [FastFlagManager::SetValue] Value change for 'DFIntTaskSchedulerTargetFps' to '9999' is pending
2023-08-05T10:48:19Z [FastFlagManager::SetValue] Value change for 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2023-08-05T10:48:19Z [FastFlagManager::SetValue] Value change for 'DFFlagDisableDPIScale' to 'True' is pending
2023-08-05T10:48:19Z [FastFlagManager::SetValue] Value change for 'DFFlagVariableDPIScale2' to 'False' is pending
2023-08-05T10:48:19Z [MainWindow::MainWindow] Initializing menu
2023-08-05T10:49:22Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=True)
2023-08-05T10:49:22Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-08-05T10:49:23Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-08-05T10:49:23Z [RobloxDeployment::GetInfo] Getting extra information...
2023-08-05T10:49:23Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2023-08-05T10:49:23Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version
2023-08-05T10:49:24Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version
2023-08-05T10:49:24Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2023-08-05T10:49:24Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-05T10:49:24Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-05T10:49:24Z [RobloxDeployment::GetInfo] https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt - Last-Modified: Wed, 02 Aug 2023 19:42:49 GMT
2023-08-05T10:49:32Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-08-05T10:49:32Z [App::OnStartup] Initializing bootstrapper
2023-08-05T10:49:32Z [App::OnStartup] Initializing bootstrapper dialog
2023-08-05T10:49:32Z [Bootstrapper::Run] Running bootstrapper
2023-08-05T10:49:32Z [Bootstrapper::SetStatus] Connecting to Roblox...
2023-08-05T10:49:32Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2023-08-05T10:49:32Z [RobloxDeployment::GetInfo] Deploy information is cached
2023-08-05T10:49:32Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-05T10:49:32Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-05T10:49:32Z [Bootstrapper::SetStatus] Installing Roblox...
2023-08-05T10:49:32Z [Bootstrapper::DownloadPackage] Downloading RobloxApp.zip (cc1550ff205e30141a524e0bc383b65a)...
2023-08-05T10:49:32Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version-6552be68b05d41a5-RobloxApp.zip
2023-08-05T10:49:32Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version-6552be68b05d41a5-RobloxApp.zip
2023-08-05T10:49:49Z [App::OnStartup] Bootstrapper task has finished
2023-08-05T10:49:49Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2023-08-05T10:49:49Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-08-05T10:49:49Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The decryption operation failed, see inner exception.)
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package) in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 1191
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package) in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 1182
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package) in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 1182
   at Bloxstrap.Bootstrapper.InstallLatestVersion() in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 753
   at Bloxstrap.Bootstrapper.Run() in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 153
   at Bloxstrap.Bootstrapper.Run() in D:\a\bloxstrap\bloxstrap\Bloxstrap\Bootstrapper.cs:line 183
   --- End of inner exception stack trace ---
**--LOG END--**

I tried it again, using the file you gave, yet it didn't work (Apologize for the late response, I seldom check Github).

**Comment by pizzaboxer** [comment]
You're so late that by now I've actually seen this dozens of times from different people, so this isn't really showing me anything new now. Though, since this seems more and more like a bug with Windows or .NET everytime I see it, I need to do a lot of troubleshooting to figure out why this is even happening. Doesn't help that it only occurs for like 0.001% of all users. If you're up for helping me troubleshoot this, I'll need you to be a lot more responsive.

**Comment by Herobrine8761** [comment]
I'll try my best to help with this, but timezones and my activity on Github will cause a lot of problem. We could use Discord if you have it though.

**Comment by 1011025m** [comment]
> We could use Discord if you have it though.

Our Discord server is linked in the README.

**Comment by pizzaboxer** [comment]
Yeah, join the server, and we can talk there. https://discord.gg/nKjV3mGq6R
