### ISSUE TITLE
Doesnt load

### ISSUE THREAD

**Issue by Voyagas** [pizzaboxer/bloxstrap#427]
![imagen_2023-07-24_191212752](https://github.com/pizzaboxer/bloxstrap/assets/140466014/e3dc875c-6187-4f9f-931b-4b85431d0f9a)

**Comment by Voyagas** [comment]
[Bloxstrap_20230725T010700Z.log](https://github.com/pizzaboxer/bloxstrap/files/12156171/Bloxstrap_20230725T010700Z.log)
Log

**Comment by Voyagas** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/140466014/89ef657b-ac1c-45ab-855d-6e2b3cad06b5)

**Comment by pizzaboxer** [comment]
What does connecting to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZFlag in your browser show, without a VPN?

**Comment by Voyagas** [comment]
still same

**Comment by Voyagas** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/140466014/d90bf322-3fe4-4adc-9619-9172d818d335)
and also this

**Comment by pizzaboxer** [comment]
> still same

What do you mean by that? What does it show?

**Comment by Voyagas** [comment]
1. the same thing that in the main post
2. roblox perfectly works without bloxstrap

**Comment by pizzaboxer** [comment]
> the same thing that in the main post

Can you show a screenshot?

**Comment by Voyagas** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/140466014/e16e1af2-0776-4439-b2bb-4b49e3fd96e7)

**Comment by Voyagas** [comment]
wait nvm
![image](https://github.com/pizzaboxer/bloxstrap/assets/140466014/64a786c6-c56f-4fa2-a081-bf6f8377565b)

**Comment by pizzaboxer** [comment]
I told you to go to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZFlag in your browser, which that isn't.

Anyway, I think what's going on here is that something isn't allowing Bloxstrap to connect to the internet, probably an antivirus or something.

**Comment by Voyagas** [comment]
i only use windows defender
![image](https://github.com/pizzaboxer/bloxstrap/assets/140466014/390df393-f0f9-4d80-bc3f-dd40b02d8f95)

**Comment by pizzaboxer** [comment]
Let's see if we can figure out what's going on. Try downloading [this build](https://github.com/pizzaboxer/bloxstrap/suites/14597247102/artifacts/827148970), run Bloxstrap.exe, and go to the Connectivity test tab. Show me what it says.

**Comment by Voyagas** [comment]
[14:12:55] Connecting to https://www.google.com...
[14:12:55] Connection failed!
[14:12:55] System.Net.Http.HttpRequestException: Host desconocido. (www.google.com:443)
 ---> System.Net.Sockets.SocketException (11001): Host desconocido.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.UI.ViewModels.Menu.ConnectivityTestViewModel.RunTest() in D:\a\bloxstrap\bloxstrap\Bloxstrap\UI\ViewModels\Menu\ConnectivityTestViewModel.cs:line 39
[14:12:55] 
[14:12:55] Connecting to https://clientsettingscdn.roblox.com...
[14:12:55] Connection failed!
[14:12:55] System.Net.Http.HttpRequestException: El nombre solicitado es válido pero no se encontraron datos del tipo solicitado. (clientsettingscdn.roblox.com:443)
 ---> System.Net.Sockets.SocketException (11004): El nombre solicitado es válido pero no se encontraron datos del tipo solicitado.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.UI.ViewModels.Menu.ConnectivityTestViewModel.RunTest() in D:\a\bloxstrap\bloxstrap\Bloxstrap\UI\ViewModels\Menu\ConnectivityTestViewModel.cs:line 54
[14:12:55] 
[14:12:55] Connecting to http://s3.amazonaws.com/setup.roblox.com/version...
[14:12:55] Connection failed!
[14:12:55] System.Net.Http.HttpRequestException: Host desconocido. (s3.amazonaws.com:80)
 ---> System.Net.Sockets.SocketException (11001): Host desconocido.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.UI.ViewModels.Menu.ConnectivityTestViewModel.RunTest() in D:\a\bloxstrap\bloxstrap\Bloxstrap\UI\ViewModels\Menu\ConnectivityTestViewModel.cs:line 71

**Comment by pizzaboxer** [comment]
No doubt, something is preventing Bloxstrap from connecting to the internet. Are you sure you have nothing on your computer that could be causing that?

**Comment by Voyagas** [comment]
what could prevent bloxstrap from connecting to the internet?

**Comment by pizzaboxer** [comment]
Are you sure Windows Defender is the only antivirus you have?

**Comment by Voyagas** [comment]
yes

**Comment by Voyagas** [comment]
uhhhhh

**Comment by Voyagas** [comment]
Hello?

**Comment by pizzaboxer** [comment]
I've already told you that something is blocking it, you just need to find what it is, since I have no idea what you have instsalled on your PC. I'll close this since it's clear this isn't a problem with Bloxstrap itself.

**Comment by Voyagas** [comment]
no
