### ISSUE TITLE
Not able to be installed

### ISSUE THREAD

**Issue by kodabkr** [pizzaboxer/bloxstrap#433]
Log file output:

2023-07-25T09:00:20Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The decryption operation failed, see inner exception.)
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory 1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory 1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory 1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   --- End of inner exception stack trace ---

Same issue as:
  #407

**Comment by pizzaboxer** [comment]
Indicates a HTTP error. Also, please send the full log, and not just an except of it.

**Comment by kodabkr** [comment]
2023-07-25T09:59:05Z [App::OnStartup] Starting Bloxstrap v2.4.0
2023-07-25T09:59:05Z [App::OnStartup] Compiled Monday, 24 July 2023 at 4:26:12 PM from commit 34bba491fb05877fc17b9dc20f09186947299a60 (tag/v2.4.0)
2023-07-25T09:59:05Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230725T095905Z.log
2023-07-25T09:59:05Z [Logger::Initialize] Finished initializing!
2023-07-25T09:59:05Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-07-25T09:59:05Z [JsonManager<Settings>::Load] Loaded successfully!
2023-07-25T09:59:05Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-07-25T09:59:05Z [JsonManager<State>::Load] Loaded successfully!
2023-07-25T09:59:05Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-07-25T09:59:05Z [JsonManager<Dictionary`2>::Load] Failed to load! (Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.)
2023-07-25T09:59:05Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '9999' is pending
2023-07-25T09:59:05Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2023-07-25T09:59:05Z [FastFlagManager::SetValue] Setting of 'DFFlagDisableDPIScale' to 'True' is pending
2023-07-25T09:59:05Z [FastFlagManager::SetValue] Setting of 'DFFlagVariableDPIScale2' to 'False' is pending
2023-07-25T09:59:05Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-07-25T09:59:05Z [App::OnStartup] Initializing bootstrapper
2023-07-25T09:59:05Z [App::OnStartup] Initializing bootstrapper dialog
2023-07-25T09:59:05Z [Bootstrapper::Run] Running bootstrapper
2023-07-25T09:59:05Z [Bootstrapper::CheckForUpdates] Checking for updates...
2023-07-25T09:59:05Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-07-25T09:59:06Z [Bootstrapper::CheckForUpdates] No updates found
2023-07-25T09:59:06Z [Bootstrapper::SetStatus] Connecting to Roblox...
2023-07-25T09:59:06Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-07-25T09:59:06Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version
2023-07-25T09:59:06Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version-b9021bd8128442aa-rbxPkgManifest.txt
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version-b9021bd8128442aa-rbxPkgManifest.txt
2023-07-25T09:59:06Z [Bootstrapper::SetStatus] Installing Roblox...
2023-07-25T09:59:06Z [Bootstrapper::DownloadPackage] RobloxApp.zip is corrupted (23485d8b3451dda95fbc4bbd34b5d0c0 != 9d0da3a1a77e5001b43e4cfce155a671)! Deleting and re-downloading...
2023-07-25T09:59:06Z [Bootstrapper::DownloadPackage] Downloading RobloxApp.zip (9d0da3a1a77e5001b43e4cfce155a671)...
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpRequestMessage] GET https://setup.rbxcdn.com/version-b9021bd8128442aa-RobloxApp.zip
2023-07-25T09:59:06Z [HttpClientLoggingHandler::HttpResponseMessage] 200 OK https://setup.rbxcdn.com/version-b9021bd8128442aa-RobloxApp.zip
2023-07-25T09:59:07Z [App::OnStartup] Bootstrapper task has finished
2023-07-25T09:59:07Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2023-07-25T09:59:07Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-07-25T09:59:07Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The decryption operation failed, see inner exception.)
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.InstallLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   --- End of inner exception stack trace ---


-------------------
This is the full log file, sorry for the inconvience

**Comment by pizzaboxer** [comment]
Seens to be suggesting that it can't download https://setup.rbxcdn.com/version-b9021bd8128442aa-RobloxApp.zip. Are you using an antivirus, VPN, or proxy of some kind?

**Comment by pizzaboxer** [comment]
Yeah, it's not something I can fix.

**Comment by kodabkr** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/90579924/b113993a-da04-4f85-ade4-49b454870427)
Thank you for trying to help anyways, i'll do some debugging on my own to see if i cant fix it.

**Comment by pizzaboxer** [comment]
> ![image](https://user-images.githubusercontent.com/90579924/255866745-b113993a-da04-4f85-ade4-49b454870427.png) Thank you for trying to help anyways, i'll do some debugging on my own to see if i cant fix it.
> 
> (This error occurs randomly, don't know what it is, i can still finish the file download if i click resume enough)

Oh, that's interesting. Try and see if these two work:
https://setup-ak.rbxcdn.com/version-b9021bd8128442aa-RobloxApp.zip
https://s3.amazonaws.com/setup.roblox.com/version-b9021bd8128442aa-RobloxApp.zip

Anyway, since it's clear this isn't a Bloxstrap problem, I'll mark this as resolved.
