### ISSUE TITLE
Reinstalling Bloxstrap (DirectoryNotFoundException)

### ISSUE THREAD

**Issue by ahysus** [pizzaboxer/bloxstrap#474]
2023-07-30T09:01:32Z [App::OnStartup] Starting Bloxstrap v2.4.0
2023-07-30T09:01:32Z [App::OnStartup] Compiled Tuesday, 25 July 2023 at 4:26:12 AM from commit 34bba491fb05877fc17b9dc20f09186947299a60 (tag/v2.4.0)
2023-07-30T09:01:32Z [Logger::Initialize] Initializing at F:\Application\Bloxstrap\Logs\Bloxstrap_20230730T090132Z.log
2023-07-30T09:01:32Z [App::OnStartup] An exception occurred when running the main thread
2023-07-30T09:01:32Z [App::OnStartup] System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Application\Bloxstrap\Logs'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
  
This problem started when I removed my ssd and used it in another pc and after I returned my ssd to my pc, bloxstrap won't start. So I tried reinstalling it and this happens. Any idea how to fix?

Note: I only have 2 disks when this happened - Local Disk (C) and Local Disk (F), after returning my ssd to my pc, Local Disk (F) sorted itself and changed F to D since I have no other extra drives

**Comment by pizzaboxer** [comment]
That is an edge case if I've ever seen one. Honestly, it would probably be best to just change the drive label back to F, since you'd have bigger problems than just Bloxstrap not working.

**Comment by ahysus** [comment]
Thanks, will do once I have the need to remove my ssd again or if I have bought the other ssd I want to buy.

**Comment by pizzaboxer** [comment]
That being said, it probably wouldn't hurt to have a prompt to detect if the install location doesn't exist anymore.
