### ISSUE TITLE
log issue?

### ISSUE THREAD

**Issue by Zombiotic** [pizzaboxer/bloxstrap#517]
System.IO.IOException: The process cannot access the file 'C:\Users\Zomb\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230730T134012Z.log' because it is being used by another process.

**Comment by Zombiotic** [comment]
3-08-06T14:07:54Z [App::OnStartup] Starting Bloxstrap v2.4.0
2023-08-06T14:07:54Z [App::OnStartup] Compiled Monday, 24 July 2023 at 2:26:12 PM from commit 34bba491fb05877fc17b9dc20f09186947299a60 (tag/v2.4.0)
2023-08-06T14:07:54Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230806T140754Z.log
2023-08-06T14:07:54Z [Logger::Initialize] Finished initializing!
2023-08-06T14:07:54Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20230730T134012Z.log'
2023-08-06T14:07:54Z [App::OnStartup] An exception occurred when running the main thread
2023-08-06T14:07:54Z [App::OnStartup] System.IO.IOException: The process cannot access the file '%UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230730T134012Z.log' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
Try out this beta 2.5.1 build, and see if the same thing happens.

https://github.com/pizzaboxer/bloxstrap/suites/14861614604/artifacts/846342136

**Comment by Zombiotic** [comment]
ok its fully functional now thank you!
