### ISSUE TITLE
Error when trying to copy invite deeplink

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#522]
```
2023-08-08T00:27:04Z [App::OnStartup] Starting Bloxstrap v2.5.0
2023-08-08T00:27:04Z [App::OnStartup] Compiled Tuesday, 1 August 2023 at 11:27:30 PM from commit dca6fc46bb0e876df9c240fcf10872e5bbc4fc44 (tag/v2.5.0)
2023-08-08T00:27:04Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2023-08-08T00:27:04Z [App::OnStartup] Performing connectivity check...
2023-08-08T00:27:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://detectportal.firefox.com/
2023-08-08T00:27:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://detectportal.firefox.com/
2023-08-08T00:27:04Z [App::OnStartup] Connectivity check finished
2023-08-08T00:27:04Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230808T002704Z.log
2023-08-08T00:27:04Z [Logger::Initialize] Finished initializing!
2023-08-08T00:27:04Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-08-08T00:27:04Z [JsonManager<Settings>::Load] Loaded successfully!
2023-08-08T00:27:04Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-08-08T00:27:04Z [JsonManager<State>::Load] Loaded successfully!
2023-08-08T00:27:04Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-08-08T00:27:04Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2023-08-08T00:27:04Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2023-08-08T00:27:04Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-08-08T00:27:04Z [JsonManager<State>::Save] Save request ignored
2023-08-08T00:27:04Z [App::OnStartup] Initializing bootstrapper
2023-08-08T00:27:04Z [App::OnStartup] Initializing bootstrapper dialog
2023-08-08T00:27:04Z [App::OnStartup] Creating singleton mutex
2023-08-08T00:27:04Z [App::OnStartup] Warning - singleton mutex already exists!
2023-08-08T00:27:04Z [Bootstrapper::Run] Running bootstrapper
2023-08-08T00:27:04Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2023-08-08T00:27:04Z [Bootstrapper::SetStatus] Connecting to Roblox...
2023-08-08T00:27:04Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2023-08-08T00:27:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-08-08T00:27:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-08-08T00:27:05Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2023-08-08T00:27:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2023-08-08T00:27:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2023-08-08T00:27:06Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2023-08-08T00:27:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-08T00:27:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-6552be68b05d41a5-rbxPkgManifest.txt
2023-08-08T00:27:06Z [JsonManager<Dictionary`2>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-08-08T00:27:06Z [JsonManager<Dictionary`2>::Save] Save complete!
2023-08-08T00:27:06Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] Checking executable flags...
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] Checking file mods...
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\!ZCANARY4.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\!ZCANARYAPPS.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\!ZCLIENTINTEGRATION1.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettingsz.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\HARMONY.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\PCClientBootstrapper.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\removingweirdshit.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] ClientSettings\StudioAppSettings.json already exists in the version folder, and is a match
2023-08-08T00:27:06Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-08-08T00:27:06Z [JsonManager<State>::Save] Save complete!
2023-08-08T00:27:06Z [Bootstrapper::ApplyModifications] Finished checking file mods
2023-08-08T00:27:06Z [Bootstrapper::CheckInstall] Checking install
2023-08-08T00:27:06Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-08-08T00:27:06Z [JsonManager<Settings>::Save] Save complete!
2023-08-08T00:27:06Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-08-08T00:27:06Z [JsonManager<State>::Save] Save complete!
2023-08-08T00:27:06Z [Bootstrapper::SetStatus] Starting Roblox...
2023-08-08T00:27:06Z [Bootstrapper::StartRoblox] Started Roblox (PID 17204)
2023-08-08T00:27:06Z [Bootstrapper::StartRoblox] Using Discord Rich Presence
2023-08-08T00:27:06Z [DiscordRichPresence::DiscordRichPresence] Established connection with Discord RPC
2023-08-08T00:27:06Z [DiscordRichPresence::DiscordRichPresence] Received ready from user arRPC (1045800378228281345)
2023-08-08T00:27:09Z [NotifyIconWrapper::InitializeContextMenu] Initializing context menu
2023-08-08T00:27:09Z [ActivityWatcher::StartWatcher] Opening Roblox log file...
2023-08-08T00:27:09Z [ActivityWatcher::StartWatcher] Opened %UserProfile%\AppData\Local\Roblox\logs\0.588.0.5880517_20230808T002707Z_Player_ADA21_last.log
2023-08-08T00:27:09Z [Bootstrapper::StartRoblox] Waiting for Roblox to close
2023-08-08T00:27:09Z [ActivityWatcher::ExamineLogEntry] Read 50 log entries
2023-08-08T00:27:10Z [ActivityWatcher::ExamineLogEntry] Joining Game (17541193/7886476c-b7b8-4da0-b049-e41e50b7d58f/10.194.3.30)
2023-08-08T00:27:10Z [ActivityWatcher::ExamineLogEntry] Server is UDMUX protected (17541193/7886476c-b7b8-4da0-b049-e41e50b7d58f/128.116.115.33)
2023-08-08T00:27:11Z [ActivityWatcher::ExamineLogEntry] Read 100 log entries
2023-08-08T00:27:11Z [ActivityWatcher::ExamineLogEntry] Joined Game (17541193/7886476c-b7b8-4da0-b049-e41e50b7d58f/128.116.115.33)
2023-08-08T00:27:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.115.33/city
2023-08-08T00:27:11Z [DiscordRichPresence::SetCurrentGame] Setting presence for Place ID 17541193
2023-08-08T00:27:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://apis.roblox.com/universes/v1/places/17541193/universe
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://apis.roblox.com/universes/v1/places/17541193/universe
2023-08-08T00:27:12Z [DiscordRichPresence::SetCurrentGame] Got Universe ID as 31874845
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://games.roblox.com/v1/games?universeIds=31874845
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://ipinfo.io/128.116.115.33/city
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.115.33/region
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://ipinfo.io/128.116.115.33/region
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.115.33/country
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://ipinfo.io/128.116.115.33/country
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://games.roblox.com/v1/games?universeIds=31874845
2023-08-08T00:27:12Z [NotifyIconWrapper::ShowAlert.6818c862] Showing alert for 10 seconds (clickHandler=True)
2023-08-08T00:27:12Z [NotifyIconWrapper::ShowAlert.6818c862] Connnected to public server: Located at Seattle, Washington, US\nClick for more information
2023-08-08T00:27:12Z [DiscordRichPresence::SetCurrentGame] Got Universe details
2023-08-08T00:27:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://thumbnails.roblox.com/v1/games/icons?universeIds=31874845&returnPolicy=PlaceHolder&size=512x512&format=Png&isCircular=false
2023-08-08T00:27:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://thumbnails.roblox.com/v1/games/icons?universeIds=31874845&returnPolicy=PlaceHolder&size=512x512&format=Png&isCircular=false
2023-08-08T00:27:13Z [DiscordRichPresence::SetCurrentGame] Got Universe thumbnail as https://tr.rbxcdn.com/71726f60d215367684252fce95fc176a/512/512/Image/Png
2023-08-08T00:27:13Z [DiscordRichPresence::UpdatePresence] Updating presence
2023-08-08T00:27:14Z [DiscordRichPresence::DiscordRichPresence] Presence updated
2023-08-08T00:27:16Z [ActivityWatcher::ExamineLogEntry] Read 150 log entries
2023-08-08T00:27:22Z [NotifyIconWrapper::ShowAlert.6818c862] Duration over, erasing current click handler
2023-08-08T00:28:16Z [ActivityWatcher::ExamineLogEntry] Read 200 log entries
2023-08-08T00:29:48Z [App::GlobalExceptionHandler] An exception occurred
2023-08-08T00:29:48Z [App::FinalizeExceptionHandling] System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Bloxstrap.UI.Elements.ContextMenu.MenuContainer.InviteDeeplinkMenuItem_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by pizzaboxer** [comment]
https://stackoverflow.com/a/17678542
