### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by 3xc223** [pizzaboxer/bloxstrap#592]
not so long ago I decided to delete bloxstrap by deleting its files now I can't download it an error pops up in this error it says about some folder but in fact this folder does not exist also I use a translator so sorry I couldn't understand me logs-2023-08- 26T15:09:32Z [App::OnStartup] Starting Bloxstrap v2.5.1
2023-08-26T15:09:32Z [App::OnStartup] Compiled Friday, 25 August 2023 at 3:28:39 AM from commit 8f084958e21a790f8e4c746fcb41b6ce5a252130 (tag/v2.5.1)
2023-08-26T15:09:32Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.1.exe
2023-08-26T15:09:32Z [Logger::Initialize] Initializing at D:\Auto Keyboard 10.0\Logs\Bloxstrap_20230826T150932Z.log
2023-08-26T15:09:32Z [App::GlobalExceptionHandler] An exception occurred
2023-08-26T15:09:32Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'D:\Auto Keyboard 10.0\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) 
![image](https://github.com/pizzaboxer/bloxstrap/assets/125866775/dc248f75-c4c7-49ac-81c0-c5bf1fd0743e)

**Comment by pizzaboxer** [comment]
Why is it installed to "Auto Keyboard 10.0"?

**Comment by 3xc223** [comment]
I do not know I specified the path to disk d also I repeat that such a folder does not exist

**Comment by pizzaboxer** [comment]
Reinstall Bloxstrap and make sure you set the install location properly.

**Comment by 3xc223** [comment]
when I open the installer, this error pops up, I do not know how to remove it, there should not have been bloxstrap files left on my PC

**Comment by pizzaboxer** [comment]
How exactly did you uninstall Bloxstrap?

**Comment by 3xc223** [comment]
by deleting the bloxstrap file folder

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap

How do you usually uninstall programs on your computer?

**Comment by 3xc223** [comment]
I followed the link and it didn't help me. I usually delete programs either through programs and components or by deleting folders

**Comment by pizzaboxer** [comment]
> I followed the link and it didn't help me.

Well, what happened when you tried to uninstall it?

**Comment by 3xc223** [comment]
nothing, this folder was transferred to the trash and I cleaned it

**Comment by pizzaboxer** [comment]
> nothing, this folder was transferred to the trash and I cleaned it

Why are you deleting the folder yourself? The guide tells you to uninstall it through the Control panel.

**Comment by 3xc223** [comment]
At that time I was small and didn't think about it

**Comment by GoingCrazyDude** [comment]
what do you mean by you were small lmao

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
