### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by suii9e** [pizzaboxer/bloxstrap#753]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can't open bloxstrap menu or anything, the logo is just a white paper sheet not the real logo and everytime i click open it won't start
![Screenshot 2023-10-07 154927](https://github.com/pizzaboxer/bloxstrap/assets/147240128/da1803a9-078e-4b43-9e90-483de3e15808)

**Comment by pizzaboxer** [comment]
Where's the log file? The preliminary instructions asks you to send it.

**Comment by suii9e** [comment]
idk what is this but here
2023-10-07T14:41:49Z [App::OnStartup] Starting Bloxstrap v2.5.0
2023-10-07T14:41:49Z [App::OnStartup] Compiled Wednesday, 2 August 2023 at 3:27:30 AM from commit dca6fc46bb0e876df9c240fcf10872e5bbc4fc44 (tag/v2.5.0)
2023-10-07T14:41:49Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.0.exe
2023-10-07T14:41:49Z [App::OnStartup] Performing connectivity check...
2023-10-07T14:41:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://detectportal.firefox.com/
2023-10-07T14:41:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://detectportal.firefox.com/
2023-10-07T14:41:50Z [App::OnStartup] Connectivity check finished
2023-10-07T14:41:50Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20231007T144150Z.log
2023-10-07T14:41:50Z [Logger::Initialize] Finished initializing!
2023-10-07T14:41:50Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-10-07T14:41:51Z [JsonManager<Settings>::Load] Loaded successfully!
2023-10-07T14:41:51Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-10-07T14:41:51Z [JsonManager<State>::Load] Loaded successfully!
2023-10-07T14:41:51Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-10-07T14:41:51Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2023-10-07T14:41:52Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2023-10-07T14:41:52Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-10-07T14:41:55Z [App::OnStartup] Initializing bootstrapper
2023-10-07T14:41:55Z [App::OnStartup] Initializing bootstrapper dialog
2023-10-07T14:41:56Z [Bootstrapper::Run] Running bootstrapper
2023-10-07T14:41:56Z [Bootstrapper::CheckForUpdates] Checking for updates...
2023-10-07T14:41:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-10-07T14:41:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-10-07T14:41:57Z [Bootstrapper::SetStatus] Getting the latest Bloxstrap...
2023-10-07T14:41:57Z [Bootstrapper::CheckForUpdates] Downloading v2.5.2...
2023-10-07T14:41:57Z [Bootstrapper::CheckForUpdates] Starting v2.5.2...
2023-10-07T14:41:57Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-10-07T14:41:57Z [JsonManager<Settings>::Save] Save complete!
2023-10-07T14:41:57Z [App::OnStartup] Bootstrapper task has finished
2023-10-07T14:41:57Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2023-10-07T14:41:57Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-10-07T14:41:57Z [App::OnStartup] System.AggregateException: One or more errors occurred. (An error occurred trying to start process '%UserProfile%\AppData\Local\Temp\Bloxstrap-v2.5.2.exe' with working directory 'C:\WINDOWS\system32'. The specified executable is not a valid application for this OS platform.)
 ---> System.ComponentModel.Win32Exception (193): An error occurred trying to start process '%UserProfile%\AppData\Local\Temp\Bloxstrap-v2.5.2.exe' with working directory 'C:\WINDOWS\system32'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.CheckForUpdates()
   at Bloxstrap.Bootstrapper.Run()
   --- End of inner exception stack trace ---

**Comment by suii9e** [comment]
![Uploading Screenshot 2023-10-07 214643.png…]()

**Comment by suii9e** [comment]
2023-10-07T14:41:49Z [App::OnStartup] Starting Bloxstrap v2.5.0
2023-10-07T14:41:49Z [App::OnStartup] Compiled Wednesday, 2 August 2023 at 3:27:30 AM from commit dca6fc46bb0e876df9c240fcf10872e5bbc4fc44 (tag/v2.5.0)
2023-10-07T14:41:49Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.0.exe
2023-10-07T14:41:49Z [App::OnStartup] Performing connectivity check...
2023-10-07T14:41:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://detectportal.firefox.com/
2023-10-07T14:41:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://detectportal.firefox.com/
2023-10-07T14:41:50Z [App::OnStartup] Connectivity check finished
2023-10-07T14:41:50Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20231007T144150Z.log
2023-10-07T14:41:50Z [Logger::Initialize] Finished initializing!
2023-10-07T14:41:50Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-10-07T14:41:51Z [JsonManager<Settings>::Load] Loaded successfully!
2023-10-07T14:41:51Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-10-07T14:41:51Z [JsonManager<State>::Load] Loaded successfully!
2023-10-07T14:41:51Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-10-07T14:41:51Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2023-10-07T14:41:52Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2023-10-07T14:41:52Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-10-07T14:41:55Z [App::OnStartup] Initializing bootstrapper
2023-10-07T14:41:55Z [App::OnStartup] Initializing bootstrapper dialog
2023-10-07T14:41:56Z [Bootstrapper::Run] Running bootstrapper
2023-10-07T14:41:56Z [Bootstrapper::CheckForUpdates] Checking for updates...
2023-10-07T14:41:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-10-07T14:41:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-10-07T14:41:57Z [Bootstrapper::SetStatus] Getting the latest Bloxstrap...
2023-10-07T14:41:57Z [Bootstrapper::CheckForUpdates] Downloading v2.5.2...
2023-10-07T14:41:57Z [Bootstrapper::CheckForUpdates] Starting v2.5.2...
2023-10-07T14:41:57Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-10-07T14:41:57Z [JsonManager<Settings>::Save] Save complete!
2023-10-07T14:41:57Z [App::OnStartup] Bootstrapper task has finished
2023-10-07T14:41:57Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2023-10-07T14:41:57Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-10-07T14:41:57Z [App::OnStartup] System.AggregateException: One or more errors occurred. (An error occurred trying to start process '%UserProfile%\AppData\Local\Temp\Bloxstrap-v2.5.2.exe' with working directory 'C:\WINDOWS\system32'. The specified executable is not a valid application for this OS platform.)
 ---> System.ComponentModel.Win32Exception (193): An error occurred trying to start process '%UserProfile%\AppData\Local\Temp\Bloxstrap-v2.5.2.exe' with working directory 'C:\WINDOWS\system32'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.CheckForUpdates()
   at Bloxstrap.Bootstrapper.Run()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
Why don't you just use the latest version?

**Comment by suii9e** [comment]
Oh sorry i didn't know! I watch yt and they said to download the v2.5.2.exe

**Comment by pizzaboxer** [comment]
> I watch yt and they said to download the v2.5.2.exe

But you're using 2.5.0.

**Comment by suii9e** [comment]
Oh sorry, i accidently write v2.5.2
