### ISSUE TITLE
[BUG] An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Glumim5** [pizzaboxer/bloxstrap#890]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2023-11-02T17:12:53Z [App::OnStartup] Starting Bloxstrap v2.5.3
2023-11-02T17:12:53Z [App::OnStartup] Compiled Wednesday, 11 October 2023 at 9:29:04 AM from commit a099d160726f4d5ac832f97a8e167ae0338193ad (tag/v2.5.3)
2023-11-02T17:12:53Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2023-11-02T17:12:53Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20231102T171253Z.log
2023-11-02T17:12:53Z [Logger::Initialize] Finished initializing!
2023-11-02T17:12:53Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2023-11-02T17:12:53Z [JsonManager<Settings>::Load] Loaded successfully!
2023-11-02T17:12:53Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2023-11-02T17:12:53Z [JsonManager<State>::Load] Loaded successfully!
2023-11-02T17:12:53Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2023-11-02T17:12:53Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2023-11-02T17:12:53Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2023-11-02T17:12:53Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2023-11-02T17:12:54Z [App::OnStartup] Initializing bootstrapper
2023-11-02T17:12:54Z [App::OnStartup] Initializing bootstrapper dialog
2023-11-02T17:12:54Z [Bootstrapper::Run] Running bootstrapper
2023-11-02T17:12:54Z [Bootstrapper::Run] Performing connectivity check...
2023-11-02T17:12:54Z [Bootstrapper::SetStatus] Connecting to Roblox...
2023-11-02T17:12:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2023-11-02T17:12:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-11-02T17:12:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2023-11-02T17:12:56Z [Bootstrapper::Run] Connectivity check finished
2023-11-02T17:12:56Z [Bootstrapper::CheckForUpdates] Checking for updates...
2023-11-02T17:12:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-11-02T17:12:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2023-11-02T17:12:56Z [Bootstrapper::CheckForUpdates] No updates found
2023-11-02T17:12:56Z [RobloxDeployment::GetInfo] Getting deploy info for channel zbeta (extraInformation=False)
2023-11-02T17:12:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2023-11-02T17:12:56Z [HttpClientLoggingHandler::ProcessResponse] 401 Unauthorized https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2023-11-02T17:12:56Z [RobloxDeployment::GetInfo] Failed to fetch deploy info!
	Status code: Unauthorized
	Response: {"errors":[{"code":5,"message":"Not authorized to perform this action."}]}
2023-11-02T17:12:56Z [App::OnStartup] Bootstrapper task has finished
2023-11-02T17:12:56Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2023-11-02T17:12:56Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-11-02T17:12:57Z [App::OnStartup] System.AggregateException: One or more errors occurred. (Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta because it returned HTTP 401 (Unauthorized))
 ---> Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta because it returned HTTP 401 (Unauthorized)
   at Bloxstrap.RobloxDeployment.GetInfo(String channel, Boolean extraInformation)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass56_0.<<OnStartup>b__1>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by Glumim5** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/115948298/f5dab266-4a00-4850-8371-36e51d1c551d)

**Comment by Glumim5** [comment]
Nevermind it's in the wiki, sorry!
