### ISSUE TITLE
ReShade Problem help

### ISSUE THREAD

**Issue by RainShinay** [pizzaboxer/bloxstrap#93]
Bloxstrap

An error occured while starting Roblox Details: System.Net.Https.HttpRequiresException: The SSL connection could not be established, see inner exception.

**Comment by RainShinay** [comment]
2023-02-18T19:26:04Z [App::OnStartup] Starting Bloxstrap v2.0.0
2023-02-18T19:26:04Z [Logger::Logger] Initialized at <UserProfileFolder>\AppData\Local\Bloxstrap\Logs\Bloxstrap_20230218T192604Z.log
2023-02-18T19:26:04Z [JsonManager<Settings>::Load] Loading JSON from <UserProfileFolder>\AppData\Local\Bloxstrap\Settings.json...
2023-02-18T19:26:04Z [JsonManager<Settings>::Load] JSON loaded successfully!
2023-02-18T19:26:04Z [JsonManager<State>::Load] Loading JSON from <UserProfileFolder>\AppData\Local\Bloxstrap\State.json...
2023-02-18T19:26:04Z [JsonManager<State>::Load] JSON loaded successfully!
2023-02-18T19:26:04Z [Bootstrapper::Run] Running bootstrapper
2023-02-18T19:26:04Z [Bootstrapper::CheckForUpdates] Checking for Bloxstrap updates...
2023-02-18T19:26:05Z [Bootstrapper::CheckForUpdates] No updates found
2023-02-18T19:26:05Z [Bootstrapper::SetStatus] Connecting to Roblox...
2023-02-18T19:26:05Z [DeployManager::GetLastDeploy] Getting deploy info for channel LIVE (timestamp=False)
2023-02-18T19:26:05Z [DeployManager::GetLastDeploy] Got JSON: {"version":"0.562.0.5620360","clientVersionUpload":"version-b467400c8f8e4097","bootstrapperVersion":"1, 6, 0, 5620360"}
2023-02-18T19:26:05Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2023-02-18T19:26:05Z [ReShade::CheckModifications] Checking ReShade modifications...
2023-02-18T19:26:06Z [ReShade::CheckModifications] Installing/Upgrading ReShade...
2023-02-18T19:26:07Z [ReShade::DownloadConfig] Downloading/Upgrading config file...
2023-02-18T19:26:07Z [JsonManager<State>::Save] Attempting to save JSON to <UserProfileFolder>\AppData\Local\Bloxstrap\State.json...
2023-02-18T19:26:07Z [JsonManager<State>::Save] JSON saved!
2023-02-18T19:26:07Z [ReShade::DownloadShaders] Downloading shaders for Stock
2023-02-18T19:26:08Z [App::OnStartup] Bootstrapper task has finished
2023-02-18T19:26:08Z [App::OnStartup] An exception occurred when running the bootstrapper
2023-02-18T19:26:08Z [App::OnStartup] System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Bloxstrap.Helpers.Integrations.ReShade.DownloadShaders(String name)
   at Bloxstrap.Helpers.Integrations.ReShade.CheckModifications()
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   --- End of inner exception stack trace ---
2023-02-18T19:31:58Z [App::Terminate] Terminating with exit code 1603
2023-02-18T19:31:58Z [JsonManager<Settings>::Save] Attempting to save JSON to <UserProfileFolder>\AppData\Local\Bloxstrap\Settings.json...
2023-02-18T19:31:58Z [JsonManager<Settings>::Save] JSON saved!
2023-02-18T19:31:58Z [JsonManager<State>::Save] Attempting to save JSON to <UserProfileFolder>\AppData\Local\Bloxstrap\State.json...
2023-02-18T19:31:58Z [JsonManager<State>::Save] JSON saved!

**Comment by RainShinay** [comment]
![image](https://user-images.githubusercontent.com/106995181/219884700-52b2422b-62bf-4bb1-8da2-bdcf951ebca1.png)

**Comment by RainShinay** [comment]
Also i downloading a RoShade before, and deleted it in 10 hours cuz sucks. But i wanna try ReShade with bloxstrap i think it will be gonna op

**Comment by Extravi** [comment]
try installing bloxstrap again

**Comment by RainShinay** [comment]
> try installing bloxstrap again

i do it 10 times lol

**Comment by pizzaboxer** [comment]
What happens when you try to access [https://github.com/crosire/reshade-shaders/archive/refs/heads/master.zip](https://github.com/crosire/reshade-shaders/archive/refs/heads/master.zip) in your browser? I have a feeling you have a proxy or a VPN enabled that's not allowing Bloxstrap to download ReShade's shaders.

**Comment by bluepilledgreat** [comment]
something seems to be blocking your connection

**Comment by RainShinay** [comment]
> What happens when you try to access https://github.com/crosire/reshade-shaders/archive/refs/heads/master.zip in your browser? I have a feeling you have a proxy or a VPN enabled that's not allowing Bloxstrap to download ReShade's shaders.

![image](https://user-images.githubusercontent.com/106995181/219944254-5aefad58-8284-404e-b1ed-1199abe3c368.png)
lol, im from Russia. How to fix?

**Comment by RainShinay** [comment]
![image](https://user-images.githubusercontent.com/106995181/219944509-efefda28-dc08-44f5-9f87-8097dce98ba1.png)
 doing with vpn, nothing.

**Comment by pizzaboxer** [comment]
Yep, seems like a proxy or something is in the way. Click on the text that says `NET::ERR_CERT_COMMON_NAME_INVALID` to show the cerificate details, and post them here.
![image](https://user-images.githubusercontent.com/41478239/219947293-2d6df603-904b-442b-9e86-de0962be2ced.png)

**Comment by pizzaboxer** [comment]
Closed for inactivity. I'll reopen if you follow up on this.
