### ISSUE TITLE
[BUG] Bloxtrap failed to start [An execpiton occurred while running Bloxtrap]

### ISSUE THREAD

**Issue by SorceryDestroyer** [pizzaboxer/bloxstrap#939]
Hello, When i try to install BloxTrap it just gives me this error when it starts: 

Error message: 

2023-11-15T14:10:56Z [App::OnStartup] Starting Bloxstrap v2.5.3
2023-11-15T14:10:56Z [App::OnStartup] Compiled Wednesday, 11 October 2023 at 9:29:04 AM from commit a099d160726f4d5ac832f97a8e167ae0338193ad (tag/v2.5.3)
2023-11-15T14:10:56Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.3.exe
2023-11-15T14:10:56Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20231115T141056Z.log
2023-11-15T14:10:56Z [App::GlobalExceptionHandler] An exception occurred
2023-11-15T14:10:56Z [App::FinalizeExceptionHandling] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Logs'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
   
   Preview of the error message:
<img width="405" alt="image" src="https://github.com/pizzaboxer/bloxstrap/assets/100327708/36e8625c-6c5e-460e-95d1-3b67d78651b9">

Can anyone help me fix this issue when starting Bloxtrap and when trying to install Bloxtrap on my Windows 11 23H2 PC?

**Comment by pizzaboxer** [comment]
...Did you attempt to uninstall it by just deleting the folder it was installed to?

**Comment by pizzaboxer** [comment]
Move it back, uninstall it, then reinstall it with the new location that you prefer.
